import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { QUESTION_BANK, CATEGORY_LIST, STARTER_QUESTION_COUNT, validateQuestionBank } from '../src/content.js';
import { shuffled } from '../src/random.js';

assert.deepEqual(validateQuestionBank(),[],'question pack validation');
assert.equal(STARTER_QUESTION_COUNT,73,'historical starter IDs stay stable');
assert.equal(QUESTION_BANK.length,325,'73 existing plus 252 new questions');
assert.equal(CATEGORY_LIST.length,20,'all established categories');
for(const category of CATEGORY_LIST){
  const added=QUESTION_BANK.slice(STARTER_QUESTION_COUNT).filter(q=>q.category===category.id);
  const expected=category.id==='braille'?24:12;
  assert.equal(added.length,expected,`${category.id} has ${expected} Migration 009 questions`);
}
assert.equal(QUESTION_BANK[73].id,'bq-en-0415','first safe expansion ID after the verified remote maximum');
assert.equal(QUESTION_BANK.at(-1).id,'bq-en-0666','final expansion ID');
const ids=new Set(QUESTION_BANK.map(q=>q.id));
assert.equal(ids.size,QUESTION_BANK.length,'unique stable question ids');
for(const q of QUESTION_BANK.slice(STARTER_QUESTION_COUNT))assert.match(q.sourceNote,/https:\/\//,`${q.id} source note`);

const source=['A','B','C','D'];
const deterministic=shuffled(source,max=>max-1);
assert.deepEqual(deterministic,source,'shuffle supports final index');
assert.notEqual(shuffled(source,()=>0),source,'shuffle can move the authored correct-first choice');
assert.deepEqual([...shuffled(source,()=>0)].sort(),source,'shuffle preserves every answer');

const html=await readFile(new URL('../index.html',import.meta.url),'utf8');
for(const id of ['home','auth','game','settings','results','announcer','assertive-announcer'])assert(html.includes(`id="${id.startsWith('announcer')?id:`view-${id}`}"`)||html.includes(`id="${id}"`),`required UI landmark ${id}`);
assert(html.includes('aria-live="polite"')&&html.includes('aria-live="assertive"'),'live regions');
assert(html.includes('id="recovery-form"')&&html.includes('Forgot Login ID?'),'login ID recovery UI');
assert(html.includes('Eight-character Login ID'),'Login ID field');
assert(!/<input[^>]*type="(?:email|password)"/i.test(html),'no email/password input fields');
assert(!html.includes('sfx-on'),'no unavailable sound-effect control');
const css=await readFile(new URL('../styles.css',import.meta.url),'utf8');
assert(css.includes(':focus-visible'),'visible focus indicator');
assert(css.includes('.high-contrast')&&css.includes('.large-text')&&css.includes('.reduce-motion'),'accessibility settings styles');
const main=await readFile(new URL('../src/main.js',import.meta.url),'utf8');
assert(!/(AudioContext|createOscillator)/.test(main),'no synthetic Web Audio effects');
assert(main.includes('displayAnswers:shuffled(q.answers)'),'answer choices are shuffled independently');
assert(html.includes('id=\"play-featured\">Play now'),'primary action says Play now');
assert(!html.includes('id=\"backend-note\"'),'no technical backend status element');
const backend=await readFile(new URL('../src/backend.js',import.meta.url),'utf8');
const uiSource=`${html}\n${main}\n${backend}`;
assert(!/service reachable|function must be installed|account service is offline|service is not set up/i.test(uiSource),'no implementation-level backend messages in the UI');
assert(!/BOOT_ERROR|backend_not_ready|service_error|invalid_request|unknown_action|origin_not_allowed|method_not_allowed|session_expired|Uncaught|SyntaxError|Deno|Edge Function|Supabase CLI/i.test(uiSource),'no backend implementation codes or runtime errors surfaced in the UI');
assert(/Something went wrong\. Please try again\./.test(main)&&/The name, Login ID, or secret answer is incorrect\. Please try again\./.test(main),'failures fall back to generic, human wording');
const categoryRender=main.slice(main.indexOf('function renderCategories'),main.indexOf('function renderModes'));
assert(categoryRender.includes('<strong>${esc(c.name)}</strong>'),'category buttons contain the category name');
assert(!/category-mark|category-count|c\.description|c\.count/.test(categoryRender),'category buttons show names only');
assert(html.includes('id=\"game-start\"')&&main.includes('Get ready!')&&main.includes("['3','2','1']")&&main.includes("'GO!'"),'ready screen and spoken countdown remain available');
assert(main.includes('Something went wrong. Please try again.')&&main.includes('Too many attempts. Please wait and try again.'),'client errors remain generic and rate limits are explained');
const migration=await readFile(new URL('../supabase/migrations/202609260001_core.sql',import.meta.url),'utf8');
for(const term of ['name_normalized text not null unique','login_id text not null unique','answer_hash text not null','enable row level security','bq_record_answer','unique(profile_id,question_id)'])assert(migration.includes(term),`schema requirement ${term}`);
const fn=await readFile(new URL('../supabase/functions/blind-quiz-api/index.ts',import.meta.url),'utf8');
for(const term of ['PBKDF2','310000','name_taken','loginId','bq_consume_attempt','token_hash','record-answer'])assert(fn.includes(term),`server feature ${term}`);
assert.equal((fn.match(/^import \{ createClient \}/gm)||[]).length,1,'one Supabase client import');
assert.equal((fn.match(/\bcreateClient\s*\(/g)||[]).length,1,'one admin client initialization');
assert.equal((fn.match(/Deno\.serve\(handler\)/g)||[]).length,1,'one Edge Function entrypoint');
for(const term of ["action==='signup'","action==='login'","action==='recover-id'","action==='logout'","action==='record-answer'","action==='profile'"])assert(fn.includes(term),`server action ${term}`);
assert(fn.includes("return json({ok:false,code:'rate_limited'},429,origin)"),'server enforces rate limits');
assert(fn.includes("p_choice:choice"),'answer rewards use the server-side answer RPC');
const logArguments=[...fn.matchAll(/console\.(?:log|error)\(([^;]*?)\);/g)].map(m=>m[1].replace(/(['"])[^'"]*\1/g,''));
assert(logArguments.every(args=>!/(?:\bSECRET\b|\bPEPPER\b|\bAuthorization\b|\btoken\b|\banswer\b|\braw\b)/i.test(args)),'never log secrets, sessions, auth headers, or secret answers');
assert(!/secret answer.{0,50}console\.log/i.test(fn),'do not log secret answers');
// Update path: Reload button and network-first service worker.
assert(/<button class="text-button" id="reload-button" type="button" aria-label="[^"]+">Reload<\/button>/.test(html),'footer Reload button exists with an aria-label');
assert(/<span class="footer-actions">[\s\S]*id="reload-button"[\s\S]*id="logout-button"[\s\S]*<\/span><\/footer>/.test(html),'Reload and Log out share the footer actions group');
assert(css.includes('footer .footer-actions{')&&css.includes('footer .footer-actions button{margin-left:0}'),'footer actions styles');
const reloadWire=main.slice(main.indexOf("$('#reload-button')"));
assert(main.includes("$('#reload-button').addEventListener('click'"),'Reload button is wired');
assert(reloadWire.includes('window.location.reload()'),'Reload button calls window.location.reload()');
assert(reloadWire.indexOf("announce('Reloading Blind Quiz to get the latest version.',true)")>-1&&reloadWire.indexOf("announce('Reloading Blind Quiz")<reloadWire.indexOf('window.location.reload()'),'reload is announced before the page reloads');
const sw=await readFile(new URL('../sw.js',import.meta.url),'utf8');
assert(sw.includes("const CACHE='blind-quiz-shell-v4'"),'service worker cache is v4');
assert(sw.includes('fetch(req)')&&sw.includes('caches.match(req)')&&sw.indexOf('fetch(req)')<sw.indexOf('caches.match(req)'),'service worker is network-first (fetch before cache)');
const swCatch=sw.slice(sw.indexOf('.catch('));
assert(sw.includes('.catch(')&&swCatch.includes('caches.match(req)')&&swCatch.includes("caches.match('./index.html')"),'offline .catch() fallback to cache and ./index.html still exists');
const manifest=JSON.parse(await readFile(new URL('../manifest.webmanifest',import.meta.url),'utf8'));
assert.equal(manifest.name.startsWith('Blind Quiz'),true);
console.log(`PASS: ${QUESTION_BANK.length} structured questions, ${CATEGORY_LIST.length} categories, shuffle/content/schema/security/accessibility source checks.`);
