// Builds the Letters to Words dictionary from SCOWL (Spell Checker Oriented Word Lists, Kevin Atkinson),
// via the npm package wordlist-english. Only the spelling-neutral "english-words" lists are used, so
// every word is spelled the same in British, American, Canadian, and Australian English.
//
//   tier 1 = SCOWL size 10 (most common words)   tier 2 = size 20   tier 3 = size 35
//
// Lowercase a-z words of 3-7 letters only (no proper nouns, abbreviations, or apostrophes), minus
// scripts/words/blocklist.txt. Output: src/words.js (used by the game) and the word list embedded
// in the bq_words seed of Migration 013 (used by the server to verify words).
//
// Usage: npm i --no-save wordlist-english@1.2.1 && node scripts/words/build-words.mjs [--check]
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const ROOT = new URL('../../', import.meta.url);
const block = new Set(readFileSync(new URL('scripts/words/blocklist.txt', ROOT), 'utf8').split('\n').filter(l => !l.startsWith('#')).join(' ').split(/\s+/).filter(Boolean));
const seen = new Set();
const tiers = [10, 20, 35].map(size => {
  const words = require(`wordlist-english/english-words-${size}.json`).filter(w => /^[a-z]{3,7}$/.test(w) && !block.has(w) && !seen.has(w));
  words.forEach(w => seen.add(w));
  return words.sort();
});
const js = `// Generated by scripts/words/build-words.mjs. Do not edit by hand.
// Source: SCOWL english-words lists, sizes 10/20/35, Copyright 2000-2016 Kevin Atkinson (permissive licence, see WORDS_LICENSE.md).
// Lowercase a-z, 3-7 letters, offensive and abbreviation-like words removed. Tier 1 is the most common.
export const WORD_TIERS = [
${tiers.map(t => `  '${t.join(' ')}'`).join(',\n')}
];
`;
const MIGRATION = new URL('supabase/migrations/202610050013_profile_changes_and_words.sql', ROOT);
const sql = readFileSync(MIGRATION, 'utf8');
const seed = tiers.map((t, i) => `  (${i + 1}, '${t.join(' ')}')`).join(',\n');
const START = '-- BEGIN GENERATED WORDS', END = '-- END GENERATED WORDS';
const nextSql = sql.replace(new RegExp(`${START}[\\s\\S]*?${END}`), `${START}\n${seed}\n${END}`);
if (process.argv.includes('--check')) {
  const ok = readFileSync(new URL('src/words.js', ROOT), 'utf8') === js && nextSql === sql;
  console.log(ok ? `Word lists in sync: ${tiers.map(t => t.length).join(' / ')} words.` : 'Word lists are out of date: run node scripts/words/build-words.mjs');
  process.exit(ok ? 0 : 1);
}
writeFileSync(new URL('src/words.js', ROOT), js);
writeFileSync(MIGRATION, nextSql);
console.log(`Wrote ${tiers.map(t => t.length).join(' / ')} words (tiers 1/2/3), ${seen.size} total.`);
