import { writeFile } from 'node:fs/promises';
import { readFileSync } from 'node:fs';
import { QUESTION_BANK, STARTER_QUESTION_COUNT, MIGRATION_009_COUNT, MIGRATION_010_COUNT, MIGRATION_011_COUNT, MIGRATION_015_COUNT, MIGRATION_016_COUNT, MIGRATION_025_COUNT, validateQuestionBank } from '../src/content.js';

const errors=validateQuestionBank();
if(errors.length)throw new Error(errors.join('\n'));
const sqlQuote=s=>`'${String(s).replaceAll("'","''")}'`;
const insert=q=>`insert into public.bq_questions(id,category,subcategory,difficulty,mode,question,answers,correct_answer,explanation,xp_reward,coin_reward,tags,language,active,source_note) values (${sqlQuote(q.id)},${sqlQuote(q.category)},${sqlQuote(q.subcategory)},${sqlQuote(q.difficulty)},${sqlQuote(q.mode)},${sqlQuote(q.question)},${sqlQuote(JSON.stringify(q.answers))}::jsonb,${sqlQuote(q.correctAnswer)},${sqlQuote(q.explanation)},${q.xp},${q.coins},array[${q.tags.map(sqlQuote).join(',')}],${sqlQuote(q.language)},${q.active},${sqlQuote(q.sourceNote)})`;
const update=' on conflict(id) do update set category=excluded.category,subcategory=excluded.subcategory,difficulty=excluded.difficulty,mode=excluded.mode,question=excluded.question,answers=excluded.answers,correct_answer=excluded.correct_answer,explanation=excluded.explanation,xp_reward=excluded.xp_reward,coin_reward=excluded.coin_reward,tags=excluded.tags,language=excluded.language,active=excluded.active,source_note=excluded.source_note;';
const seed=QUESTION_BANK.map(q=>insert(q)+update).join('\n');
await writeFile(new URL('../supabase/seed.sql',import.meta.url),`-- Generated only after content validation. Run after the core migration.\nbegin;\n${seed}\ncommit;\n`);
// Migration 009 is already applied remotely; it is regenerated byte-for-byte from the same rows and must never change.
const added=QUESTION_BANK.slice(STARTER_QUESTION_COUNT,STARTER_QUESTION_COUNT+MIGRATION_009_COUNT);
const migration=added.map(q=>insert(q)+';').join('\n');
await writeFile(new URL('../supabase/migrations/202610030009_expand_question_bank.sql',import.meta.url),`-- Migration 009: add ${added.length} reviewed questions. Apply once after migrations 001-008.\n-- Prepared 2026-10-03; application must be confirmed by the project owner.\nbegin;\n${migration}\ncommit;\n`);
// Migration 010: additive only. `on conflict (id) do nothing` makes it safe to re-run and it never touches existing rows.
// Migration 010 is already applied remotely; it is regenerated byte-for-byte and must never change.
const added010=QUESTION_BANK.slice(STARTER_QUESTION_COUNT+MIGRATION_009_COUNT,STARTER_QUESTION_COUNT+MIGRATION_009_COUNT+MIGRATION_010_COUNT);
const migration010=added010.map(q=>insert(q)+' on conflict (id) do nothing;').join('\n');
await writeFile(new URL('../supabase/migrations/202610050010_add_200_questions.sql',import.meta.url),`-- Migration 010: add ${added010.length} reviewed questions (${added010[0]?.id} to ${added010.at(-1)?.id}).\n-- Additive only. Requires migrations 001-009, which are already applied and must not be rerun.\n-- Applied only by .github/workflows/apply-migration-010.yml through the Supabase Management API query endpoint.\nbegin;\n${migration010}\ncommit;\n`);
// Migration 011: additive only, same rules as Migration 010.
// Migration 011 is already applied remotely; it is regenerated byte-for-byte and must never change.
const start011=STARTER_QUESTION_COUNT+MIGRATION_009_COUNT+MIGRATION_010_COUNT;
const added011=QUESTION_BANK.slice(start011,start011+MIGRATION_011_COUNT);
const migration011=added011.map(q=>insert(q)+' on conflict (id) do nothing;').join('\n');
await writeFile(new URL('../supabase/migrations/202610050011_add_200_more_questions.sql',import.meta.url),`-- Migration 011: add ${added011.length} reviewed questions (${added011[0]?.id} to ${added011.at(-1)?.id}).\n-- Additive only. Requires migrations 001-010, which are already applied and must not be rerun.\n-- Applied only by .github/workflows/apply-migration-011.yml through the Supabase Management API query endpoint.\nbegin;\n${migration011}\ncommit;\n`);
// Migration 015: additive only (Medical, Math, Physics, Chemistry, Biology), same rules as Migrations 010 and 011.
const added015=QUESTION_BANK.slice(start011+MIGRATION_011_COUNT,start011+MIGRATION_011_COUNT+MIGRATION_015_COUNT);
const migration015=added015.map(q=>insert(q)+' on conflict (id) do nothing;').join('\n');
await writeFile(new URL('../supabase/migrations/202610050015_add_five_categories.sql',import.meta.url),`-- Migration 015: add ${added015.length} reviewed questions in five new categories (${added015[0]?.id} to ${added015.at(-1)?.id}).\n-- Medical, Math, Physics, Chemistry and Biology, 20 each. Additive only; approved by the owner on 5 Oct 2026.\n-- Requires migrations 001-014, which are already applied and must not be rerun.\n-- Applied only by .github/workflows/apply-migration-015.yml through the Supabase Management API query endpoint.\nbegin;\n${migration015}\ncommit;\n`);
// Migration 016: 250 additive questions (10 per category) plus the owner-approved word reward (5 XP + 1 coin on a first find).
const start016=start011+MIGRATION_011_COUNT+MIGRATION_015_COUNT;
const added016=QUESTION_BANK.slice(start016,start016+MIGRATION_016_COUNT);
const migration016=added016.map(q=>insert(q)+' on conflict (id) do nothing;').join('\n');
const function016=readFileSync(new URL('./migration-016-function.sql',import.meta.url),'utf8');
await writeFile(new URL('../supabase/migrations/202610060016_questions_and_word_reward.sql',import.meta.url),`-- Migration 016: add ${added016.length} reviewed questions (${added016[0]?.id} to ${added016.at(-1)?.id}), 10 in each of the 25 categories,\n-- and change the Letters to Words reward to 5 XP + 1 coin the first time a player finds a word (repeats pay nothing).\n-- Additive questions plus one create-or-replace of bq_record_word; approved by the owner on 6 Oct 2026.\n-- Requires migrations 001-015, which are already applied and must not be rerun.\n-- Applied only by .github/workflows/apply-migration-016.yml through the Supabase Management API query endpoint.\nbegin;\n${migration016}\n${function016}commit;\n`);
console.log(`Migration 016: ${added016.length} questions and the word reward function.`);
console.log(`Wrote ${QUESTION_BANK.length} validated seed questions, Migration 009 with ${added.length} rows (unchanged), Migration 010 with ${added010.length} rows (unchanged), Migration 011 with ${added011.length} rows (unchanged), and Migration 015 with ${added015.length} new rows.`);

// Migration 025 preserves all PR #5 rows and adds PR #6's 500 new questions after ID 1416.
// It is prepared only; never rewrite or reapply PR #5's already-published migrations.
if (MIGRATION_025_COUNT !== 500) throw new Error(`Migration 025 must contain 500 rows; found ${MIGRATION_025_COUNT}`);
const start025 = QUESTION_BANK.length - MIGRATION_025_COUNT;
const added025 = QUESTION_BANK.slice(start025);
const migration025 = added025.map(q => insert(q) + ' on conflict (id) do nothing;').join('\n');
const categoryCounts025 = new Map();
for (const question of added025) categoryCounts025.set(question.category, (categoryCounts025.get(question.category) || 0) + 1);
if (categoryCounts025.size !== 25 || [...categoryCounts025.values()].some(count => count !== 20)) {
  throw new Error('Migration 025 must add exactly 20 questions in each of the 25 categories');
}
await writeFile(new URL('../supabase/migrations/202610080025_expand_question_bank.sql', import.meta.url), `-- Migration 025: add 500 reviewed questions, exactly 20 in each of the 25 categories.\n-- IDs bq-en-1417 through bq-en-1916. Prepared 2026-10-08; not applied remotely.\n-- Additive only; preserves all PR #5 migrations 009-024.\nbegin;\n${migration025}\ncommit;\n`);
console.log(`Prepared Migration 025 with ${added025.length} questions (20 in each of 25 categories); it has not been applied.`);
