import { QUESTION_BANK, CATEGORY_LIST, validateQuestionBank } from './content.js';
import { callApi, getSession, setSession } from './backend.js';
import { shuffled } from './random.js';
const $=(s,root=document)=>root.querySelector(s), $$=(s,root=document)=>[...root.querySelectorAll(s)];
const state={view:'home',category:'general',mode:'classic',difficulty:'easy',questions:[],index:0,score:0,answered:false,timer:null,timeLeft:0,locked:false,settings:{largeText:false,highContrast:false,reducedMotion:false,speech:true,timer:0},profile:null};
const modes=[['classic','Classic Quiz','Four real answers, one clear choice.'],['rapid','Rapid Fire','Eight questions with a 15-second clock.'],['random','Random Mix','Questions drawn from the full playable pack.'],['vocabulary','Vocabulary','Meanings, context, and spelling.'],['abbreviations','Abbreviations','Decode common short forms.'],['braille','Braille','Explore letters through six-dot patterns.']];
const announce=(text,urgent=false)=>{if(!state.settings.speech)return;const el=$(urgent?'#assertive-announcer':'#announcer');el.textContent='';setTimeout(()=>el.textContent=text,30)};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function go(view,{focus}={}){$$('.view').forEach(v=>{v.hidden=true});$(`#view-${view}`).hidden=false;state.view=view;window.scrollTo(0,0);if(focus){const el=$(focus);setTimeout(()=>el?.focus(),60)}else setTimeout(()=>{const h=$(`#view-${view} h1`);h?.setAttribute('tabindex','-1');h?.focus()},30)}
function top(){const s=getSession();$('#top-meta').textContent=s?.profile?.name?`${s.profile.name} · Login ID account`:'';$('#logout-button').hidden=!s}
function renderCategories(){const host=$('#category-list');host.innerHTML='';for(const c of CATEGORY_LIST){const b=document.createElement('button');b.type='button';b.className='category-button';b.dataset.category=c.id;b.innerHTML=`<strong>${esc(c.name)}</strong>`;host.append(b)}}
function renderModes(){const host=$('#mode-list');host.innerHTML='';for(const [id,name,desc] of modes){const b=document.createElement('button');b.type='button';b.className='mode-button';b.dataset.mode=id;b.innerHTML=`<strong>${esc(name)}</strong><small>${esc(desc)}</small>`;host.append(b)}}
function esc(v){return String(v).replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]))}
function setAuthTab(tab){$$('[data-auth-tab]').forEach(b=>{const on=b.dataset.authTab===tab;b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on))});$('#login-form').hidden=tab!=='login';$('#signup-form').hidden=tab!=='signup';$('#recovery-form').hidden=true;$('#signup-success').hidden=true;$('#auth-title').textContent=tab==='login'?'Log in to play':'Create your account';if(tab==='login'){applyRemembered();$(loginFocus()).focus()}else $('#signup-name').focus()}
function showError(id,msg){const e=$(id);e.textContent=msg;e.hidden=false;announce(msg,true)}
// One-tap sign in: only Name and Login ID are remembered on this device. The secret answer is never stored.
const REMEMBER_KEY='blindquiz.remembered.v1';
function getRemembered(){try{const r=JSON.parse(localStorage.getItem(REMEMBER_KEY)||'null');return r&&typeof r.name==='string'&&/^[A-Z0-9]{8}$/.test(r.loginId||'')?{name:r.name,loginId:r.loginId}:null}catch{return null}}
function rememberDevice(name,loginId){try{localStorage.setItem(REMEMBER_KEY,JSON.stringify({name,loginId}))}catch{}}
function forgetDevice(){try{localStorage.removeItem(REMEMBER_KEY)}catch{}}
function applyRemembered(){const r=getRemembered(),box=$('#remembered-device');if(!r){box.hidden=true;return false}const typed=$('#login-name').value.trim();if(typed&&typed!==r.name){box.hidden=true;return false}$('#login-name').value=r.name;$('#login-id').value=r.loginId;$('#remembered-copy').textContent=`Welcome back, ${r.name}. Your name and Login ID are filled in from this device. Just type your secret answer.`;box.hidden=false;lookupQuestion();announce(`Welcome back, ${r.name}. Your name and Login ID ${r.loginId.split('').join(' ')} are already filled in. Type your secret answer to sign in.`);return true}
const loginFocus=()=>getRemembered()?'#login-answer':'#login-name';
const genericLogin='The name, Login ID, or secret answer is incorrect. Please try again.';
let questionLookupTimer,signupNameTimer;
async function checkSignupName(){const name=$('#signup-name').value.trim(),status=$('#signup-name-status');status.textContent='';if(name.length<2)return;try{const data=await callApi('check-name',{name});status.textContent=data.available?'Name is available.':'This name is already registered. Please choose another name.';if(!data.available)announce(status.textContent,true)}catch{status.textContent='Name availability will be checked when you create the account.'}}
async function lookupQuestion(){const name=$('#login-name').value.trim(),loginId=$('#login-id').value.trim().toUpperCase();if(name.length<2||loginId.length!==8)return;try{const d=await callApi('secret-question',{name,loginId});$('#question-context').textContent=d.question||'Secret question';$('#question-context').hidden=false}catch{$('#question-context').hidden=true}}
async function signUp(e){e.preventDefault();$('#signup-error').hidden=true;const name=$('#signup-name').value.trim(),selection=$('#secret-question').value,question=selection==='custom'?$('#custom-question').value.trim():selection,answer=$('#signup-answer').value.trim(),btn=$('#signup-form button[type=submit]');if(name.length<2||!question||answer.length<2){showError('#signup-error','Please complete each field with at least two characters.');return}btn.disabled=true;btn.textContent='Creating account…';announce('Creating account. Please wait.');try{const data=await callApi('signup',{name,question,answer});$('#signup-success').hidden=false;$('#new-login-id').textContent=data.loginId;$('#signup-form').hidden=true;$('#login-form').hidden=true;$('#auth-title').textContent='Account created';$('#copy-login-id').focus();announce(`Your account has been created successfully. Your Login ID is ${data.loginId}.`,true)}catch(err){const message=err.message==='name_taken'?'This name is already registered. Please choose another name.':err.message==='rate_limited'?'Too many attempts. Please wait and try again.':'Something went wrong. Please try again.';showError('#signup-error',message)}finally{btn.disabled=false;btn.innerHTML='Create account <span aria-hidden="true">→</span>'}}
async function login(e){e.preventDefault();$('#login-error').hidden=true;const name=$('#login-name').value.trim(),loginId=$('#login-id').value.trim().toUpperCase(),answer=$('#login-answer').value.trim(),btn=$('#login-form button[type=submit]');if(!name||loginId.length!==8||!answer){showError('#login-error','Enter your name, 8-character Login ID, and secret answer.');return}btn.disabled=true;announce('Signing in. Please wait.');try{const d=await callApi('login',{name,loginId,answer});setSession({token:d.token,expiresAt:d.expiresAt,profile:d.profile});rememberDevice(d.profile?.name||name,loginId);$('#login-answer').value='';state.profile=d.profile;top();if(d.firstLogin){$('#welcome-title').textContent=`Welcome to Blind Quiz, ${d.profile.name}.` ;$('#welcome-copy').textContent='Your quiz journey begins now.';go('welcome',{focus:'#welcome-continue'});announce(`Login successful. Welcome to Blind Quiz, ${d.profile.name}. Your quiz journey begins now.`)}else{go('home',{focus:'#play-featured'});announce(`Login successful. Welcome, ${d.profile.name}.`)}}catch(err){showError('#login-error',err.message==='rate_limited'?'Too many attempts. Please wait and try again.':genericLogin)}finally{btn.disabled=false}}
async function recoverLoginId(e){e.preventDefault();$('#recovery-error').hidden=true;const name=$('#recovery-name').value.trim(),sel=$('#recovery-question').value,question=sel==='custom'?$('#recovery-custom-question').value.trim():sel,answer=$('#recovery-answer').value.trim();if(!name||!question||!answer){showError('#recovery-error','Complete each recovery field.');return}const btn=$('#recovery-form button[type=submit]');btn.disabled=true;try{const d=await callApi('recover-id',{name,question,answer});$('#recovered-id').textContent=d.loginId;$('#recovery-result').hidden=false;$('#copy-recovered-id').focus();announce(`Your Login ID is ${d.loginId}.`,true)}catch(err){showError('#recovery-error',err.message==='rate_limited'?'Too many attempts. Please wait and try again.':'The recovery details are incorrect. Please check them and try again.')}finally{btn.disabled=false}}
function poolFor(category,mode){let pool=QUESTION_BANK.filter(q=>category==='general'||q.category===category);if(mode==='vocabulary')pool=pool.filter(q=>q.category==='vocabulary');if(mode==='abbreviations')pool=pool.filter(q=>q.category==='abbreviations');if(mode==='braille')pool=pool.filter(q=>q.category==='braille');return pool}
function transformQuestion(q){return {...q,displayQuestion:q.question,displayAnswers:shuffled(q.answers),displayCorrect:q.correctAnswer,displayExplain:q.explanation}}
function startRound(category='general',mode='classic'){if(state.locked)return;state.category=category;state.mode=mode;let pool=poolFor(category,mode);if(!pool.length){announce('There are not enough questions in this category yet.',true);return}pool=shuffled(pool);const n=mode==='rapid'?8:Math.min(10,pool.length);state.questions=pool.slice(0,n).map(transformQuestion);state.index=0;state.score=0;state.answered=false;state.locked=true;state.roundTimer=mode==='rapid'?15:Number(state.settings.timer);$('#round-label').textContent=`${(modes.find(m=>m[0]===mode)?.[1]||mode).toUpperCase()} · ${(CATEGORY_LIST.find(c=>c.id===category)?.name||'MIXED').toUpperCase()}`;$('#game-start').disabled=false;$('#game-start').hidden=false;$('#game-start').textContent='Play Quiz';$('#game-tools').hidden=true;$('#round-progress').textContent=`${n} questions`;$('#progress-meter').style.width='0%';$('#phase-label').textContent='READY WHEN YOU ARE';$('#game-title').innerHTML='Make some room<br>for a new question.';$('#game-copy').textContent='When you start, listen for the countdown. The first question begins after GO.';go('game',{focus:'#game-start'});state.locked=false}
async function countdownAndBegin(){if(state.locked)return;state.locked=true;const b=$('#game-start');b.disabled=true;b.textContent='Starting…';$('#phase-label').textContent='GET READY';$('#game-title').textContent='Get ready!';$('#game-copy').textContent='Your round is about to begin.';tone(460,.08);announce('Get ready!');await sleep(1050);for(const n of ['3','2','1']){$('#game-title').textContent=n;$('#game-copy').textContent='';tone(610,.08,'triangle');announce(n,true);await sleep(1120)}$('#game-title').textContent='GO!';tone(790,.28,'sine',.07);announce('GO!',true);await sleep(950);state.locked=false;$('#game-tools').hidden=false;showQuestion()}
function showQuestion(){clearTimer();const q=state.questions[state.index];if(!q){finishRound();return}state.answered=false;$('#phase-label').textContent=q.category.toUpperCase()+' · '+q.difficulty.toUpperCase();$('#round-progress').textContent=`Question ${state.index+1} of ${state.questions.length}`;$('#progress-meter').style.width=`${state.index/state.questions.length*100}%`;$('#game-title').textContent=`Question ${state.index+1}. ${q.displayQuestion}`;$('#game-title').className='question-text';$('#game-title').setAttribute('tabindex','-1');const stage=$('#game-stage');stage.querySelector('.game-copy')?.remove();stage.querySelector('.answer-list')?.remove();stage.querySelector('.feedback')?.remove();stage.querySelector('.next-question')?.remove();const list=document.createElement('div');list.className='answer-list';list.setAttribute('role','group');list.setAttribute('aria-label','Answer choices');q.displayAnswers.forEach((answer,i)=>{const btn=document.createElement('button');btn.type='button';btn.className='answer-button';btn.textContent=answer;btn.dataset.index=String(i);btn.addEventListener('click',()=>chooseAnswer(answer,btn));list.append(btn)});stage.append(list);const fb=document.createElement('p');fb.className='feedback';stage.append(fb);$('#game-start').hidden=true;$('#round-progress').textContent=`Question ${state.index+1} of ${state.questions.length}`;$('#game-title').focus();startTimer();}
function startTimer(){const seconds=Number(state.roundTimer??state.settings.timer);if(!seconds)return;state.timeLeft=seconds;const warnAt=[10,5,3,2,1];state.timer=setInterval(()=>{state.timeLeft--;if(warnAt.includes(state.timeLeft))announce(`${state.timeLeft} seconds remaining.`);if(state.timeLeft<=0){clearTimer();timeExpired()}},1000)}function clearTimer(){if(state.timer)clearInterval(state.timer);state.timer=null}
function offerNextQuestion(){const next=document.createElement('button');next.type='button';next.className='button button-hot next-question';next.textContent=state.index+1>=state.questions.length?'View results':'Next question';next.addEventListener('click',advance,{once:true});$('#game-stage').append(next)}
async function chooseAnswer(answer,button){if(state.answered)return;state.answered=true;clearTimer();const q=state.questions[state.index],correct=answer===q.displayCorrect;if(correct){state.score++;button.classList.add('correct')}else{button.classList.add('incorrect');$$('.answer-button').forEach(b=>{if(b.textContent===q.displayCorrect)b.classList.add('correct')});}$$('.answer-button').forEach(b=>b.disabled=true);const fb=$('.feedback');fb.textContent=correct?`Correct. ${q.displayExplain}`:`Not quite. The answer is ${q.displayCorrect}. ${q.displayExplain}`;const session=getSession();if(session&&q.displayAnswers.length===4){try{const saved=await callApi('record-answer',{questionId:q.id,choice:answer});state.profile=saved.profile;setSession({...session,profile:saved.profile});top();if(saved.correct!==correct)fb.textContent=`${saved.correct?'Correct.':'Not quite.'} ${saved.explanation||q.displayExplain} ${saved.xp?`Earned ${saved.xp} XP and ${saved.coins} coins.`:''}`;}catch{fb.textContent+=` We could not save this answer to your profile, but you can continue your round.`}}announce(fb.textContent,true);offerNextQuestion()}
function timeExpired(){if(state.answered)return;state.answered=true;const q=state.questions[state.index];$$('.answer-button').forEach(b=>{b.disabled=true;if(b.textContent===q.displayCorrect)b.classList.add('correct')});$('.feedback').textContent=`Time's up. The answer is ${q.displayCorrect}. ${q.displayExplain}`;announce($('.feedback').textContent,true);offerNextQuestion()}
function advance(){state.index++;if(state.index>=state.questions.length){finishRound();return}showQuestion()}
function finishRound(){clearTimer();$('#progress-meter').style.width='100%';go('results');$('#result-score').textContent=`${state.score} correct out of ${state.questions.length}`;$('#result-message').textContent=state.score===state.questions.length?'A perfect round. Every answer landed.':state.score>=Math.ceil(state.questions.length*.7)?'Strong round. Keep that rhythm.':'Every question is another clue for next time.';announce(`Round complete. ${state.score} correct out of ${state.questions.length}.`,true)}
function repeatQuestion(){const q=state.questions[state.index];if(q)announce(`Question ${state.index+1}. ${q.displayQuestion}`,true)}
function loadSettings(){try{Object.assign(state.settings,JSON.parse(localStorage.getItem('bq.settings')||'{}'))}catch{}$('#large-text').checked=state.settings.largeText;$('#high-contrast').checked=state.settings.highContrast;$('#reduced-motion').checked=state.settings.reducedMotion;$('#speech-on').checked=state.settings.speech;$('#timer-choice').value=state.settings.timer;document.body.classList.toggle('large-text',state.settings.largeText);document.body.classList.toggle('high-contrast',state.settings.highContrast);document.body.classList.toggle('reduce-motion',state.settings.reducedMotion)}
function saveSettings(){state.settings={largeText:$('#large-text').checked,highContrast:$('#high-contrast').checked,reducedMotion:$('#reduced-motion').checked,speech:$('#speech-on').checked,timer:Number($('#timer-choice').value)};localStorage.setItem('bq.settings',JSON.stringify(state.settings));loadSettings();announce('Settings saved.');go('home',{focus:'#settings-open'})}
function wire(){
 $('#play-featured').addEventListener('click',()=>startRound('general','classic'));$('#category-list').addEventListener('click',e=>{const b=e.target.closest('[data-category]');if(b)startRound(b.dataset.category,'classic')});$('#mode-list').addEventListener('click',e=>{const b=e.target.closest('[data-mode]');if(b)startRound('general',b.dataset.mode)});$('#random-category').addEventListener('click',()=>{const options=CATEGORY_LIST.filter(c=>c.count>=4);const c=options[Math.floor(Math.random()*options.length)];startRound(c.id,'classic')});$$('[data-category="braille"]').forEach(b=>b.addEventListener('click',()=>startRound('braille','classic')));
 $('#account-open').addEventListener('click',()=>{setAuthTab('login');go('auth',{focus:loginFocus()})});$('#forget-device').addEventListener('click',()=>{forgetDevice();$('#login-name').value='';$('#login-id').value='';$('#login-answer').value='';$('#question-context').hidden=true;$('#remembered-device').hidden=true;$('#login-name').focus();announce('This device no longer remembers your name and Login ID.')});$$('[data-auth-tab]').forEach(b=>b.addEventListener('click',()=>setAuthTab(b.dataset.authTab)));$('#login-form').addEventListener('submit',login);$('#signup-form').addEventListener('submit',signUp);$('#recovery-form').addEventListener('submit',recoverLoginId);$('#recover-open').addEventListener('click',()=>{$('#login-form').hidden=true;$('#signup-form').hidden=true;$('#recovery-form').hidden=false;$('#recovery-result').hidden=true;$('#auth-title').textContent='Recover your Login ID';$('#recovery-name').focus()});$('#recovery-back').addEventListener('click',()=>{setAuthTab('login');$('#recovery-form').hidden=true;$('#login-form').hidden=false});$('#recovery-question').addEventListener('change',()=>{$('#recovery-custom-wrap').hidden=$('#recovery-question').value!=='custom';if(!$('#recovery-custom-wrap').hidden)$('#recovery-custom-question').focus()});$('#copy-recovered-id').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('#recovered-id').textContent);announce('Login ID copied.')}catch{announce('Copy is unavailable. Select the Login ID text to copy it.')}});$('#signup-name').addEventListener('input',()=>{clearTimeout(signupNameTimer);signupNameTimer=setTimeout(checkSignupName,450)});$('#secret-question').addEventListener('change',()=>{$('#custom-question-wrap').hidden=$('#secret-question').value!=='custom';if(!$('#custom-question-wrap').hidden)$('#custom-question').focus()});['#login-name','#login-id'].forEach(sel=>$(sel).addEventListener('input',()=>{clearTimeout(questionLookupTimer);questionLookupTimer=setTimeout(lookupQuestion,500)}));$('#copy-login-id').addEventListener('click',async()=>{const id=$('#new-login-id').textContent;try{await navigator.clipboard.writeText(id);announce('Login ID copied.')}catch{const r=document.createRange();r.selectNodeContents($('#new-login-id'));getSelection().removeAllRanges();getSelection().addRange(r);announce('Select and copy your Login ID.')}});$('#continue-login').addEventListener('click',()=>{setAuthTab('login');$('#login-name').value=$('#signup-name').value;$('#login-id').value=$('#new-login-id').textContent;go('auth',{focus:'#login-answer'})});
 $('#game-start').addEventListener('click',countdownAndBegin);$('#repeat-question').addEventListener('click',repeatQuestion);$('#read-status').addEventListener('click',()=>announce(`Question ${state.index+1} of ${state.questions.length}. Score ${state.score}.`));$('#play-again').addEventListener('click',()=>startRound(state.category,state.mode));$('#settings-open').addEventListener('click',()=>go('settings'));$('#reload-button').addEventListener('click',()=>{announce('Reloading Blind Quiz to get the latest version.',true);setTimeout(()=>window.location.reload(),500)});$('#save-settings').addEventListener('click',saveSettings);$('#welcome-continue').addEventListener('click',()=>go('home',{focus:'#play-featured'}));$('#profile-auth').addEventListener('click',()=>{ setAuthTab('login');go('auth',{focus:loginFocus()})});$('#logout-button').addEventListener('click',async()=>{try{await callApi('logout')}catch{}setSession(null);state.profile=null;top();announce('You are logged out.');go('home',{focus:'#account-open'})});$$('[data-go]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.go)));$('#login-name').addEventListener('input',()=>$('#question-context').hidden=true);
}
function init(){renderCategories();renderModes();$('#question-count').textContent=QUESTION_BANK.length;const errors=validateQuestionBank();if(errors.length){console.error('Question validation errors',errors);announce('Some question data needs review.');}loadSettings();wire();top();try{if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})}catch{}announce('Blind Quiz ready. Choose a category or start a round.')}
init();
