import { QUESTION_BANK, CATEGORY_LIST, validateQuestionBank } from './content.js';
import { callApi, checkBackend, getSession, setSession } from './backend.js';
const $=(s,root=document)=>root.querySelector(s), $$=(s,root=document)=>[...root.querySelectorAll(s)];
const state={view:'home',category:'general',mode:'classic',difficulty:'easy',questions:[],index:0,score:0,answered:false,timer:null,timeLeft:0,locked:false,settings:{largeText:false,highContrast:false,reducedMotion:false,speech:true,sfx:true,timer:0},profile:null};
const modes=[['classic','Classic Quiz','Four real answers, one clear choice.'],['rapid','Rapid Fire','Eight questions with a 15-second clock.'],['random','Random Mix','Questions drawn from the full playable pack.'],['vocabulary','Vocabulary','Meanings, context, and spelling.'],['abbreviations','Abbreviations','Decode common short forms.'],['braille','Braille','Explore letters through six-dot patterns.']];
const announce=(text,urgent=false)=>{if(!state.settings.speech)return;const el=$(urgent?'#assertive-announcer':'#announcer');el.textContent='';setTimeout(()=>el.textContent=text,30)};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function tone(freq=540,duration=.07,type='sine',vol=.045){if(!state.settings.sfx)return;try{const c=new (window.AudioContext||window.webkitAudioContext)(),o=c.createOscillator(),g=c.createGain();o.type=type;o.frequency.value=freq;g.gain.value=vol;o.connect(g);g.connect(c.destination);o.start();g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+duration);o.stop(c.currentTime+duration);o.onended=()=>c.close()}catch{}}
function go(view,{focus}={}){$$('.view').forEach(v=>{v.hidden=true});$(`#view-${view}`).hidden=false;state.view=view;window.scrollTo(0,0);if(focus){const el=$(focus);setTimeout(()=>el?.focus(),60)}else setTimeout(()=>{const h=$(`#view-${view} h1`);h?.setAttribute('tabindex','-1');h?.focus()},30)}
function top(){const s=getSession();$('#top-meta').textContent=s?.profile?.name?`${s.profile.name} · Login ID account`:'';$('#logout-button').hidden=!s}
function renderCategories(){const host=$('#category-list');host.innerHTML='';for(const c of CATEGORY_LIST){const b=document.createElement('button');b.type='button';b.className='category-button';b.dataset.category=c.id;b.innerHTML=`<span class="category-mark">SIGNAL ${String(CATEGORY_LIST.indexOf(c)+1).padStart(2,'0')}</span><strong>${esc(c.name)}</strong><span class="category-count">${c.count} starter questions · ${esc(c.description)}</span>`;host.append(b)}}
function renderModes(){const host=$('#mode-list');host.innerHTML='';for(const [id,name,desc] of modes){const b=document.createElement('button');b.type='button';b.className='mode-button';b.dataset.mode=id;b.innerHTML=`<strong>${esc(name)}</strong><small>${esc(desc)}</small>`;host.append(b)}}
function esc(v){return String(v).replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]))}
function setAuthTab(tab){$$('[data-auth-tab]').forEach(b=>{const on=b.dataset.authTab===tab;b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on))});$('#login-form').hidden=tab!=='login';$('#signup-form').hidden=tab!=='signup';$('#recovery-form').hidden=true;$('#signup-success').hidden=true;$('#auth-title').textContent=tab==='login'?'Log in to play':'Create your account';(tab==='login'?$('#login-name'):$('#signup-name')).focus()}
function showError(id,msg){const e=$(id);e.textContent=msg;e.hidden=false;announce(msg,true)}
const genericLogin='The name, Login ID, or secret answer is incorrect. Please try again.';
let questionLookupTimer,signupNameTimer;
async function checkSignupName(){const name=$('#signup-name').value.trim(),status=$('#signup-name-status');status.textContent='';if(name.length<2)return;try{const data=await callApi('check-name',{name});status.textContent=data.available?'Name is available.':'This name is already registered. Please choose another name.';if(!data.available)announce(status.textContent,true)}catch{status.textContent='Name availability will be checked when you create the account.'}}
async function lookupQuestion(){const name=$('#login-name').value.trim(),loginId=$('#login-id').value.trim().toUpperCase();if(name.length<2||loginId.length!==8)return;try{const d=await callApi('secret-question',{name,loginId});$('#question-context').textContent=d.question||'Secret question';$('#question-context').hidden=false}catch{$('#question-context').hidden=true}}
async function signUp(e){e.preventDefault();$('#signup-error').hidden=true;const name=$('#signup-name').value.trim(),selection=$('#secret-question').value,question=selection==='custom'?$('#custom-question').value.trim():selection,answer=$('#signup-answer').value.trim(),btn=$('#signup-form button[type=submit]');if(name.length<2||!question||answer.length<2){showError('#signup-error','Please complete each field with at least two characters.');return}btn.disabled=true;btn.textContent='Creating account…';announce('Creating account. Please wait.');try{const data=await callApi('signup',{name,question,answer});$('#signup-success').hidden=false;$('#new-login-id').textContent=data.loginId;$('#signup-form').hidden=true;$('#login-form').hidden=true;$('#auth-title').textContent='Account created';$('#copy-login-id').focus();announce(`Your account has been created successfully. Your Login ID is ${data.loginId}.`,true)}catch(err){const message=err.message==='name_taken'?'This name is already registered. Please choose another name.':err.message==='backend_not_ready'?'Account service is not set up yet. Please try again later.':err.message==='rate_limited'?'Too many attempts. Please wait and try again.':'Something went wrong. Please try again.';showError('#signup-error',message)}finally{btn.disabled=false;btn.innerHTML='Create account <span aria-hidden="true">→</span>'}}
async function login(e){e.preventDefault();$('#login-error').hidden=true;const name=$('#login-name').value.trim(),loginId=$('#login-id').value.trim().toUpperCase(),answer=$('#login-answer').value.trim(),btn=$('#login-form button[type=submit]');if(!name||loginId.length!==8||!answer){showError('#login-error','Enter your name, 8-character Login ID, and secret answer.');return}btn.disabled=true;announce('Signing in. Please wait.');try{const d=await callApi('login',{name,loginId,answer});setSession({token:d.token,expiresAt:d.expiresAt,profile:d.profile});state.profile=d.profile;top();if(d.firstLogin){$('#welcome-title').textContent=`Welcome to Blind Quiz, ${d.profile.name}.` ;$('#welcome-copy').textContent='Your quiz journey begins now.';go('welcome',{focus:'#welcome-continue'});announce(`Login successful. Welcome to Blind Quiz, ${d.profile.name}. Your quiz journey begins now.`)}else{go('home',{focus:'#play-featured'});announce(`Login successful. Welcome, ${d.profile.name}.`)}}catch(err){showError('#login-error',err.message==='rate_limited'?'Too many attempts. Please wait and try again.':genericLogin)}finally{btn.disabled=false}}
async function recoverLoginId(e){e.preventDefault();$('#recovery-error').hidden=true;const name=$('#recovery-name').value.trim(),sel=$('#recovery-question').value,question=sel==='custom'?$('#recovery-custom-question').value.trim():sel,answer=$('#recovery-answer').value.trim();if(!name||!question||!answer){showError('#recovery-error','Complete each recovery field.');return}const btn=$('#recovery-form button[type=submit]');btn.disabled=true;try{const d=await callApi('recover-id',{name,question,answer});$('#recovered-id').textContent=d.loginId;$('#recovery-result').hidden=false;$('#copy-recovered-id').focus();announce(`Your Login ID is ${d.loginId}.`,true)}catch(err){showError('#recovery-error',err.message==='rate_limited'?'Too many attempts. Please wait and try again.':'The recovery details are incorrect. Please check them and try again.')}finally{btn.disabled=false}}
function poolFor(category,mode){let pool=QUESTION_BANK.filter(q=>category==='general'?['animals','birds','nature','instruments','science','geography','india','history','technology','sports','civics','economics','music','abbreviations','vocabulary','braille'].includes(q.category):q.category===category);if(mode==='vocabulary')pool=pool.filter(q=>q.category==='vocabulary');if(mode==='abbreviations')pool=pool.filter(q=>q.category==='abbreviations');if(mode==='braille')pool=pool.filter(q=>q.category==='braille');return pool}
function transformQuestion(q,mode){if(mode==='truefalse'||mode==='yesno'){const valid=Math.random()>.35;return {...q,displayQuestion:q.question,displayAnswers:mode==='truefalse'?['True','False']:['Yes','No'],displayCorrect:valid?(mode==='truefalse'?'True':'Yes'):(mode==='truefalse'?'False':'No'),displayExplain:q.explanation}}if(mode==='odd'){const correct=q.answers.find(a=>a!==q.correctAnswer)||q.answers[1];return {...q,displayQuestion:`Which answer does not belong with the others? ${q.question}`,displayAnswers:q.answers,displayCorrect:q.correctAnswer,displayExplain:q.explanation}}return {...q,displayQuestion:q.question,displayAnswers:q.answers,displayCorrect:q.correctAnswer,displayExplain:q.explanation}}
function startRound(category='general',mode='classic'){if(state.locked)return;state.category=category;state.mode=mode;let pool=poolFor(category,mode);if(!pool.length){announce('There are not enough questions in this category yet.',true);return}pool=pool.slice().sort(()=>Math.random()-.5);const n=mode==='rapid'?8:Math.min(10,pool.length);state.questions=pool.slice(0,n).map(q=>transformQuestion(q,mode));state.index=0;state.score=0;state.answered=false;state.locked=true;state.roundTimer=mode==='rapid'?15:Number(state.settings.timer);$('#round-label').textContent=`${(modes.find(m=>m[0]===mode)?.[1]||mode).toUpperCase()} · ${(CATEGORY_LIST.find(c=>c.id===category)?.name||'MIXED').toUpperCase()}`;$('#game-start').disabled=false;$('#game-start').hidden=false;$('#game-start').textContent='Play Quiz';$('#game-tools').hidden=true;$('#round-progress').textContent=`${n} questions`;$('#progress-meter').style.width='0%';$('#phase-label').textContent='READY WHEN YOU ARE';$('#game-title').innerHTML='Make some room<br>for a new question.';$('#game-copy').textContent='When you start, listen for the countdown. The first question begins after GO.';go('game',{focus:'#game-start'});state.locked=false}
async function countdownAndBegin(){if(state.locked)return;state.locked=true;const b=$('#game-start');b.disabled=true;b.textContent='Starting…';$('#phase-label').textContent='GET READY';$('#game-title').textContent='Get ready!';$('#game-copy').textContent='Your round is about to begin.';tone(460,.08);announce('Get ready!');await sleep(1050);for(const n of ['3','2','1']){$('#game-title').textContent=n;$('#game-copy').textContent='';tone(610,.08,'triangle');announce(n,true);await sleep(1120)}$('#game-title').textContent='GO!';tone(790,.28,'sine',.07);announce('GO!',true);await sleep(950);state.locked=false;$('#game-tools').hidden=false;showQuestion()}
function showQuestion(){clearTimer();const q=state.questions[state.index];if(!q){finishRound();return}state.answered=false;$('#phase-label').textContent=q.category.toUpperCase()+' · '+q.difficulty.toUpperCase();$('#round-progress').textContent=`Question ${state.index+1} of ${state.questions.length}`;$('#progress-meter').style.width=`${state.index/state.questions.length*100}%`;$('#game-title').textContent=`Question ${state.index+1}. ${q.displayQuestion}`;$('#game-title').className='question-text';$('#game-title').setAttribute('tabindex','-1');const stage=$('#game-stage');stage.querySelector('.game-copy')?.remove();stage.querySelector('.answer-list')?.remove();stage.querySelector('.feedback')?.remove();const list=document.createElement('div');list.className='answer-list';list.setAttribute('role','group');list.setAttribute('aria-label','Answer choices');q.displayAnswers.forEach((answer,i)=>{const btn=document.createElement('button');btn.type='button';btn.className='answer-button';btn.textContent=answer;btn.dataset.index=String(i);btn.addEventListener('click',()=>chooseAnswer(answer,btn));list.append(btn)});stage.append(list);const fb=document.createElement('p');fb.className='feedback';fb.setAttribute('aria-live',state.settings.speech?'polite':'off');stage.append(fb);$('#game-start').hidden=true;$('#round-progress').textContent=`Question ${state.index+1} of ${state.questions.length}`;$('#game-title').focus();startTimer();}
function startTimer(){const seconds=Number(state.roundTimer??state.settings.timer);if(!seconds)return;state.timeLeft=seconds;const warnAt=[10,5,3,2,1];state.timer=setInterval(()=>{state.timeLeft--;if(warnAt.includes(state.timeLeft))announce(`${state.timeLeft} seconds remaining.`);if(state.timeLeft<=0){clearTimer();timeExpired()}},1000)}function clearTimer(){if(state.timer)clearInterval(state.timer);state.timer=null}
async function chooseAnswer(answer,button){if(state.answered)return;state.answered=true;clearTimer();const q=state.questions[state.index],correct=answer===q.displayCorrect;if(correct){state.score++;button.classList.add('correct');tone(700,.12,'sine')}else{button.classList.add('incorrect');$$('.answer-button').forEach(b=>{if(b.textContent===q.displayCorrect)b.classList.add('correct')});tone(190,.18,'square');}$$('.answer-button').forEach(b=>b.disabled=true);const fb=$('.feedback');fb.textContent=correct?`Correct. ${q.displayExplain}`:`Not quite. The answer is ${q.displayCorrect}. ${q.displayExplain}`;announce(fb.textContent,true);const session=getSession();if(session&&q.displayAnswers.length===4){try{const saved=await callApi('record-answer',{questionId:q.id,choice:answer});state.profile=saved.profile;setSession({...session,profile:saved.profile});top();if(saved.correct!==correct)fb.textContent=`${saved.correct?'Correct.':'Not quite.'} ${saved.explanation||q.displayExplain} ${saved.xp?`Earned ${saved.xp} XP and ${saved.coins} coins.`:''}`;}catch{fb.textContent+=` Your answer is not synced; account service unavailable.`}}setTimeout(()=>advance(),1150)}
function timeExpired(){if(state.answered)return;state.answered=true;const q=state.questions[state.index];$$('.answer-button').forEach(b=>{b.disabled=true;if(b.textContent===q.displayCorrect)b.classList.add('correct')});$('.feedback').textContent=`Time's up. The answer is ${q.displayCorrect}. ${q.displayExplain}`;announce($('.feedback').textContent,true);tone(140,.3,'sawtooth');setTimeout(()=>advance(),1400)}
function advance(){state.index++;if(state.index>=state.questions.length){finishRound();return}showQuestion()}
function finishRound(){clearTimer();$('#progress-meter').style.width='100%';go('results');$('#result-score').textContent=`${state.score} correct out of ${state.questions.length}`;$('#result-message').textContent=state.score===state.questions.length?'A perfect round. Every answer landed.':state.score>=Math.ceil(state.questions.length*.7)?'Strong round. Keep that rhythm.':'Every question is another clue for next time.';announce(`Round complete. ${state.score} correct out of ${state.questions.length}.`,true);tone(540,.2)}
function repeatQuestion(){const q=state.questions[state.index];if(q)announce(`Question ${state.index+1}. ${q.displayQuestion}`,true)}
function loadSettings(){try{Object.assign(state.settings,JSON.parse(localStorage.getItem('bq.settings')||'{}'))}catch{}$('#large-text').checked=state.settings.largeText;$('#high-contrast').checked=state.settings.highContrast;$('#reduced-motion').checked=state.settings.reducedMotion;$('#speech-on').checked=state.settings.speech;$('#sfx-on').checked=state.settings.sfx;$('#timer-choice').value=state.settings.timer;document.body.classList.toggle('large-text',state.settings.largeText);document.body.classList.toggle('high-contrast',state.settings.highContrast);document.body.classList.toggle('reduce-motion',state.settings.reducedMotion)}
function saveSettings(){state.settings={largeText:$('#large-text').checked,highContrast:$('#high-contrast').checked,reducedMotion:$('#reduced-motion').checked,speech:$('#speech-on').checked,sfx:$('#sfx-on').checked,timer:Number($('#timer-choice').value)};localStorage.setItem('bq.settings',JSON.stringify(state.settings));loadSettings();announce('Settings saved.');go('home',{focus:'#settings-open'})}
function wire(){
 $('#play-featured').addEventListener('click',()=>startRound('general','classic'));$('#category-list').addEventListener('click',e=>{const b=e.target.closest('[data-category]');if(b)startRound(b.dataset.category,'classic')});$('#mode-list').addEventListener('click',e=>{const b=e.target.closest('[data-mode]');if(b)startRound('general',b.dataset.mode)});$('#random-category').addEventListener('click',()=>{const options=CATEGORY_LIST.filter(c=>c.count>=4);const c=options[Math.floor(Math.random()*options.length)];startRound(c.id,'classic')});$$('[data-category="braille"]').forEach(b=>b.addEventListener('click',()=>startRound('braille','classic')));
 $('#account-open').addEventListener('click',()=>{setAuthTab('login');go('auth',{focus:'#login-name'})});$$('[data-auth-tab]').forEach(b=>b.addEventListener('click',()=>setAuthTab(b.dataset.authTab)));$('#login-form').addEventListener('submit',login);$('#signup-form').addEventListener('submit',signUp);$('#recovery-form').addEventListener('submit',recoverLoginId);$('#recover-open').addEventListener('click',()=>{$('#login-form').hidden=true;$('#signup-form').hidden=true;$('#recovery-form').hidden=false;$('#recovery-result').hidden=true;$('#auth-title').textContent='Recover your Login ID';$('#recovery-name').focus()});$('#recovery-back').addEventListener('click',()=>{setAuthTab('login');$('#recovery-form').hidden=true;$('#login-form').hidden=false});$('#recovery-question').addEventListener('change',()=>{$('#recovery-custom-wrap').hidden=$('#recovery-question').value!=='custom';if(!$('#recovery-custom-wrap').hidden)$('#recovery-custom-question').focus()});$('#copy-recovered-id').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('#recovered-id').textContent);announce('Login ID copied.')}catch{announce('Copy is unavailable. Select the Login ID text to copy it.')}});$('#signup-name').addEventListener('input',()=>{clearTimeout(signupNameTimer);signupNameTimer=setTimeout(checkSignupName,450)});$('#secret-question').addEventListener('change',()=>{$('#custom-question-wrap').hidden=$('#secret-question').value!=='custom';if(!$('#custom-question-wrap').hidden)$('#custom-question').focus()});['#login-name','#login-id'].forEach(sel=>$(sel).addEventListener('input',()=>{clearTimeout(questionLookupTimer);questionLookupTimer=setTimeout(lookupQuestion,500)}));$('#copy-login-id').addEventListener('click',async()=>{const id=$('#new-login-id').textContent;try{await navigator.clipboard.writeText(id);announce('Login ID copied.')}catch{const r=document.createRange();r.selectNodeContents($('#new-login-id'));getSelection().removeAllRanges();getSelection().addRange(r);announce('Select and copy your Login ID.')}});$('#continue-login').addEventListener('click',()=>{setAuthTab('login');$('#login-name').value=$('#signup-name').value;$('#login-id').value=$('#new-login-id').textContent;go('auth',{focus:'#login-answer'})});
 $('#game-start').addEventListener('click',countdownAndBegin);$('#repeat-question').addEventListener('click',repeatQuestion);$('#read-status').addEventListener('click',()=>announce(`Question ${state.index+1} of ${state.questions.length}. Score ${state.score}.`));$('#play-again').addEventListener('click',()=>startRound(state.category,state.mode));$('#settings-open').addEventListener('click',()=>go('settings'));$('#save-settings').addEventListener('click',saveSettings);$('#welcome-continue').addEventListener('click',()=>go('home',{focus:'#play-featured'}));$('#profile-auth').addEventListener('click',()=>{ setAuthTab('login');go('auth')});$('#logout-button').addEventListener('click',async()=>{try{await callApi('logout')}catch{}setSession(null);state.profile=null;top();announce('You are logged out.');go('home',{focus:'#account-open'})});$$('[data-go]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.go)));$('#login-name').addEventListener('input',()=>$('#question-context').hidden=true);
}
async function init(){renderCategories();renderModes();$('#question-count').textContent=QUESTION_BANK.length;const errors=validateQuestionBank();if(errors.length){console.error('Question validation errors',errors);announce('Some question data needs review.');}loadSettings();wire();top();$('#backend-note').textContent='Connecting to account service…';const online=await checkBackend();$('#backend-note').textContent=online?'Account service reachable. Account features require the Blind Quiz server function to be installed.':'Account service is offline. You can still play the downloaded question pack.';try{if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js')}catch{}if(!online)announce('Blind Quiz ready. Offline question pack available.');else announce('Blind Quiz ready. Choose a category or start a round.')}
init();
