// Migration 016: 250 reviewed questions, 10 in each of the 25 categories (bq-en-1167..1416).
// Same format as expansion-questions.js: [category, subcategory, difficulty, question, correct, wrong1, wrong2, wrong3, explanation].
// The correct answer is authored first; the game shuffles every question before display.
export const MIGRATION_016_ROWS = [
// Animals
['animals','Mammals','easy','Which slow-moving animal spends most of its life hanging upside down in rainforest trees?','Sloth','Koala','Lemur','Raccoon','Sloths live in Central and South American rainforests and move very slowly.'],
['animals','Mammals','easy','What is a baby goat called?','Kid','Calf','Foal','Cub','A young goat is called a kid.'],
['animals','Mammals','easy','Which African animal is famous for its black and white stripes?','Zebra','Okapi','Tapir','Hyena','Every zebra has its own unique pattern of black and white stripes.'],
['animals','Reptiles','easy','Which reptile carries a hard shell on its back?','Tortoise','Iguana','Gecko','Cobra','A tortoise has a hard shell made of bone covered by tough plates.'],
['animals','Mammals','medium','Which animal is the largest living land carnivore?','Polar bear','Lion','Tiger','Grizzly bear','Adult male polar bears are the largest land carnivores alive today.'],
['animals','Behavior','medium','What is it called when an animal blends into its surroundings to hide?','Camouflage','Migration','Hibernation','Mimicry of sound','Camouflage lets an animal match its background so predators or prey do not notice it.'],
['animals','Amphibians','medium','Through what can many frogs absorb water and oxygen besides the mouth?','Their skin','Their eyes','Their toes only','Their tongue','Frogs have thin, moist skin that can take in water and some oxygen.'],
['animals','Invertebrates','medium','Which sea creature has no brain or heart and is mostly water?','Jellyfish','Crab','Seahorse','Clam','Jellyfish are about 95% water and have a simple nerve net instead of a brain.'],
['animals','Mammals','hard','Which mammal lays eggs, along with the platypus?','Echidna','Armadillo','Hedgehog','Pangolin','Echidnas and platypuses are monotremes, the only egg-laying mammals.'],
['animals','Senses','hard','What do bats use to find insects in the dark by bouncing sounds off them?','Echolocation','Infrared vision','Magnetic sense','Electroreception','Many bats send out high-pitched calls and listen for echoes to locate prey.'],
// Birds
['birds','Species','easy','Which black bird is known for being very clever and even using tools?','Crow','Pigeon','Swan','Duck','Crows can solve puzzles and use sticks as tools to get food.'],
['birds','Species','easy','Which seabird has a big throat pouch for scooping up fish?','Pelican','Seagull','Puffin','Heron','A pelican uses its stretchy throat pouch to catch fish.'],
['birds','Behavior','easy','What do most birds build to lay their eggs in?','A nest','A burrow of ice','A hive','A web','Most birds build nests to hold and protect their eggs.'],
['birds','Species','easy','Which large bird cannot fly and is native to Australia?','Emu','Kiwi','Ostrich','Rhea','The emu is a large flightless bird found only in Australia.'],
['birds','Anatomy','medium','What are birds\' bones like inside, which helps them fly?','Many are hollow and light','Solid and heavy','Filled with water','Made of cartilage only','Many bird bones are hollow with internal struts, making them light but strong.'],
['birds','Behavior','medium','Which bird drums on tree trunks with its beak to find insects?','Woodpecker','Sparrow','Kingfisher','Swallow','Woodpeckers peck into wood to find insects and make nest holes.'],
['birds','Species','medium','Which rainforest bird has a huge, brightly coloured beak?','Toucan','Hornbill','Flamingo','Heron','Toucans of Central and South America have very large, colourful bills.'],
['birds','Behavior','medium','What is the name for the dawn singing of many birds together?','Dawn chorus','Morning call','Sun song','Flock tune','Many birds sing together around sunrise in what is called the dawn chorus.'],
['birds','Species','hard','Which is the smallest bird in the world?','Bee hummingbird','Goldcrest','Sunbird','Wren','The bee hummingbird of Cuba is about 5 to 6 centimetres long.'],
['birds','Anatomy','hard','What is the stomach part called where birds store food before digesting it?','Crop','Gizzard','Cloaca','Keel','The crop is a pouch in the throat where many birds store food temporarily.'],
// Nature
['nature','Plants','easy','What part of a plant makes seeds after a flower is pollinated?','Fruit','Root','Leaf','Stem','After pollination, the flower\'s ovary develops into a fruit that holds the seeds.'],
['nature','Weather','easy','What do we call frozen water that falls as soft white flakes?','Snow','Hail','Fog','Dew','Snow forms when water vapour freezes into ice crystals in clouds.'],
['nature','Earth','easy','What is the hot melted rock under Earth\'s surface called?','Magma','Lava rock','Granite','Sand','Molten rock below the surface is magma; when it reaches the surface it is called lava.'],
['nature','Water','easy','What is the continuous movement of water between land, sea and sky called?','The water cycle','The food chain','The rock cycle','The tide','In the water cycle water evaporates, condenses into clouds and falls as rain or snow.'],
['nature','Ecosystems','medium','What is a food chain?','A series showing who eats whom','A list of farm crops','A chain of grocery stores','A ranking of animal sizes','A food chain shows how energy passes from plants to animals that eat them.'],
['nature','Weather','medium','What instrument measures air pressure?','Barometer','Anemometer','Hygrometer','Seismograph','A barometer measures atmospheric pressure, which helps forecast weather.'],
['nature','Rivers','medium','What is the place where a river begins called?','Its source','Its mouth','Its delta','Its bank','A river starts at its source, often a spring, lake or glacier.'],
['nature','Ecosystems','medium','Which type of organism breaks down dead plants and animals?','Decomposer','Producer','Predator','Herbivore','Decomposers such as fungi and bacteria break down dead matter and recycle nutrients.'],
['nature','Earth','hard','What is a tsunami usually caused by?','An undersea earthquake','A strong breeze','A full moon','A thunderstorm','Most tsunamis are triggered by earthquakes that shift the sea floor.'],
['nature','Plants','hard','What are plants that lose all their leaves in autumn called?','Deciduous','Evergreen','Coniferous','Succulent','Deciduous trees shed their leaves every year, usually in autumn.'],
// Musical instruments
['instruments','Strings','easy','How many strings does a standard guitar have?','Six','Four','Five','Twelve','A standard acoustic or electric guitar has six strings.'],
['instruments','Percussion','easy','Which instrument has wooden bars struck with mallets?','Xylophone','Harp','Trumpet','Violin','A xylophone has tuned wooden bars played with mallets.'],
['instruments','Percussion','easy','What is a set of drums and cymbals played by one person in a band called?','Drum kit','Orchestra','Xylophone','Tambourine','A drum kit usually includes a snare drum, bass drum, toms and cymbals.'],
['instruments','Keyboard','easy','What colours are the keys on a standard piano?','Black and white','Red and blue','Green and white','Brown and gold','Piano keys are white for natural notes and black for sharps and flats.'],
['instruments','Strings','medium','Which large string instrument is played with its strings plucked by the fingers and has a triangular frame?','Harp','Cello','Mandolin','Banjo','The harp has strings stretched inside a frame and is played by plucking.'],
['instruments','Wind','medium','Which small wind instrument has reeds and is played by breathing in and out through holes?','Harmonica','Bagpipe','Recorder','Piccolo','The harmonica has metal reeds that sound when you blow or draw air.'],
['instruments','Indian','medium','Which long South Indian double-reed wind instrument is played at temples and weddings?','Nadaswaram','Shehnai','Bansuri','Harmonium','The nadaswaram is a loud double-reed instrument from South India.'],
['instruments','Brass','medium','Which brass instrument has three valves and is the highest-pitched common brass instrument?','Trumpet','Tuba','Trombone','French horn','The trumpet usually has three valves and plays the highest notes in the brass section.'],
['instruments','Wind','hard','Which woodwind instrument uses a double reed and plays the lowest notes in the woodwind section?','Bassoon','Clarinet','Piccolo','Flute','The bassoon is a double-reed instrument with a low range.'],
['instruments','Indian','hard','Which instrument is Ustad Amjad Ali Khan famous for playing?','Sarod','Sitar','Santoor','Sarangi','Amjad Ali Khan is a celebrated master of the sarod.'],
// Science
['science','Space','easy','What is the closest star to Earth?','The Sun','Sirius','Polaris','Alpha Centauri A','The Sun is the nearest star to Earth.'],
['science','Matter','easy','What are the three common states of matter?','Solid, liquid and gas','Hot, warm and cold','Hard, soft and sticky','Big, medium and small','Matter is commonly found as a solid, a liquid or a gas.'],
['science','Tools','easy','Which tool do scientists use to see things too small for the eye?','Microscope','Telescope','Thermometer','Compass','A microscope magnifies tiny objects such as cells.'],
['science','Space','easy','How many planets are in our solar system?','Eight','Nine','Seven','Ten','There are eight planets since Pluto was reclassified as a dwarf planet in 2006.'],
['science','Energy','medium','What kind of energy is stored in a stretched rubber band?','Elastic potential energy','Nuclear energy','Sound energy','Chemical energy','Stretching a rubber band stores elastic potential energy.'],
['science','Light','medium','What do we call a material that lets no light pass through?','Opaque','Transparent','Translucent','Reflective','Opaque objects block light completely.'],
['science','Space','medium','Which planet is known for its Great Red Spot, a giant storm?','Jupiter','Mars','Saturn','Venus','The Great Red Spot is a huge storm on Jupiter.'],
['science','Matter','medium','What is the process of a liquid turning into a solid called?','Freezing','Melting','Boiling','Condensation','Freezing is the change from liquid to solid.'],
['science','Space','hard','Which planet spins on its side, with an axis tilted about 98 degrees?','Uranus','Neptune','Saturn','Mercury','Uranus is tilted so much that it rolls around the Sun on its side.'],
['science','Body','hard','Which part of the eye controls how much light enters?','Iris','Retina','Lens','Cornea','The coloured iris changes the size of the pupil to control incoming light.'],
// Geography
['geography','Capitals','easy','What is the capital of the United Kingdom?','London','Manchester','Edinburgh','Dublin','London is the capital of the United Kingdom.'],
['geography','Capitals','easy','What is the capital of Germany?','Berlin','Munich','Frankfurt','Vienna','Berlin is the capital of Germany.'],
['geography','Capitals','easy','What is the capital of Spain?','Madrid','Barcelona','Lisbon','Seville','Madrid is the capital of Spain.'],
['geography','Physical','easy','Which is the highest mountain in the world above sea level?','Mount Everest','K2','Kangchenjunga','Mont Blanc','Mount Everest is about 8,849 metres above sea level.'],
['geography','Capitals','medium','What is the capital of China?','Beijing','Shanghai','Hong Kong','Guangzhou','Beijing is the capital of China.'],
['geography','Rivers','medium','Which river flows through Baghdad?','Tigris','Euphrates','Jordan','Indus','Baghdad lies on the Tigris River.'],
['geography','Countries','medium','In which country is the ancient Inca city of Machu Picchu?','Peru','Mexico','Chile','Bolivia','Machu Picchu stands high in the Andes of Peru.'],
['geography','Physical','medium','Which narrow strait separates Europe from Africa?','Strait of Gibraltar','Bosporus','Strait of Hormuz','Strait of Malacca','The Strait of Gibraltar is about 14 kilometres wide at its narrowest.'],
['geography','Countries','hard','Which country has the most time zones, including overseas territories?','France','Russia','United States','China','Counting its overseas territories, France spans 12 time zones.'],
['geography','Physical','hard','Which lake is the deepest in the world?','Lake Baikal','Lake Superior','Lake Victoria','Lake Tanganyika','Lake Baikal in Siberia is about 1,640 metres deep.'],
// India
['india','Symbols','easy','What is the national fruit of India?','Mango','Banana','Jackfruit','Apple','The mango is India\'s national fruit.'],
['india','Culture','easy','Which harvest festival of Kerala is known for flower carpets called pookalam?','Onam','Pongal','Baisakhi','Bihu','Onam is celebrated in Kerala with pookalam, boat races and feasts.'],
['india','Places','easy','Which state is famous for its backwaters and houseboats?','Kerala','Goa','Punjab','Rajasthan','Kerala\'s backwaters are a network of lagoons and canals.'],
['india','Places','easy','Which Indian city is known as the City of Joy?','Kolkata','Mumbai','Chennai','Pune','Kolkata is often called the City of Joy.'],
['india','Places','medium','In which state is the Sun Temple at Konark?','Odisha','Gujarat','Karnataka','Bihar','The 13th-century Konark Sun Temple is in Odisha.'],
['india','Culture','medium','Bharatanatyam is a classical dance from which state?','Tamil Nadu','Kerala','Odisha','Manipur','Bharatanatyam originated in Tamil Nadu.'],
['india','Science','medium','Who was the first woman of Indian origin to go to space?','Kalpana Chawla','Sunita Williams','Tessy Thomas','Ritu Karidhal','Kalpana Chawla flew on the Space Shuttle Columbia in 1997.'],
['india','Places','medium','In which city is the Gateway of India?','Mumbai','Delhi','Kolkata','Chennai','The Gateway of India stands on the waterfront in Mumbai.'],
['india','Science','hard','Which mission made India the first country to land near the Moon\'s south pole, in 2023?','Chandrayaan-3','Mangalyaan','Chandrayaan-1','Gaganyaan','Chandrayaan-3\'s Vikram lander touched down on 23 August 2023.'],
['india','Geography','hard','Which is the highest mountain peak located entirely within India?','Nanda Devi','Kangchenjunga','Kamet','Trishul','Nanda Devi in Uttarakhand (7,816 m) is the highest peak entirely in India; Kangchenjunga is higher but lies on the India–Nepal border.'],
// History
['history','World','easy','Which very long wall was built over centuries to protect ancient China?','The Great Wall of China','Hadrian\'s Wall','The Berlin Wall','The Western Wall','The Great Wall of China stretches thousands of kilometres.'],
['history','Inventions','easy','Who is credited with inventing the light bulb that became widely used?','Thomas Edison','Isaac Newton','Galileo Galilei','Charles Darwin','Thomas Edison developed a practical, long-lasting light bulb in 1879.'],
['history','Art','easy','Who painted the Mona Lisa?','Leonardo da Vinci','Pablo Picasso','Vincent van Gogh','Michelangelo','Leonardo da Vinci painted the Mona Lisa in the early 1500s.'],
['history','Explorers','easy','Which explorer reached the Americas in 1492?','Christopher Columbus','Vasco da Gama','James Cook','Marco Polo','Christopher Columbus reached the Caribbean in 1492.'],
['history','Explorers','medium','Which Portuguese explorer reached India by sea in 1498?','Vasco da Gama','Ferdinand Magellan','Bartolomeu Dias','Amerigo Vespucci','Vasco da Gama reached Calicut in 1498.'],
['history','Ancient','medium','Which empire built a vast network of roads and the Colosseum?','Roman Empire','Persian Empire','Ottoman Empire','Mongol Empire','The Romans built the Colosseum and thousands of kilometres of roads.'],
['history','India','medium','In which year did the Dandi Salt March take place?','1930','1920','1942','1947','Gandhi led the Salt March to Dandi in March and April 1930.'],
['history','India','medium','Which Mughal emperor was known for religious tolerance and for his court of the Nine Jewels?','Akbar','Babur','Jahangir','Aurangzeb','Akbar\'s court included the famous Navaratnas, or Nine Jewels.'],
['history','India','hard','Who founded the Mughal Empire in India?','Babur','Akbar','Humayun','Aurangzeb','Babur founded the Mughal Empire after the First Battle of Panipat in 1526.'],
['history','World','hard','Who was the first woman to win a Nobel Prize?','Marie Curie','Mother Teresa','Rosalind Franklin','Ada Lovelace','Marie Curie won the Nobel Prize in Physics in 1903.'],
// Technology
['technology','Shortcuts','easy','Which key combination copies selected text on most Windows computers?','Ctrl + C','Ctrl + V','Ctrl + Z','Alt + F4','Ctrl + C copies; Ctrl + V pastes.'],
['technology','Hardware','easy','Which device shows pictures and text from a computer?','Monitor','Keyboard','Mouse','Speaker','A monitor is the display screen of a computer.'],
['technology','Software','easy','What do we call a small program installed on a phone?','App','Cable','Router','Chip','App is short for application, a program for phones and computers.'],
['technology','Hardware','easy','Which part of a phone takes photos?','Camera','Battery','SIM card','Speaker','The camera captures photos and videos.'],
['technology','Internet','medium','What is a search engine used for?','Finding information on the web','Charging a phone','Typing faster','Storing photos only','Search engines such as Google help people find web pages.'],
['technology','Hardware','medium','What is a USB flash drive mainly used for?','Storing and carrying files','Cooling the computer','Connecting to Wi-Fi','Charging the screen','A flash drive is small portable storage that plugs into a USB port.'],
['technology','Accessibility','medium','What does screen magnification software do?','Enlarges what is on the screen','Reads the screen aloud only','Turns off the screen','Prints the screen','Magnifiers enlarge screen content for people with low vision.'],
['technology','Security','medium','What makes a strong password?','Long and mixing letters, numbers and symbols','Your name','Your birthday','The word password','Long, varied passwords are much harder to guess.'],
['technology','History','hard','Who is known as the father of the computer?','Charles Babbage','Alan Turing','Bill Gates','Tim Berners-Lee','Charles Babbage designed the Analytical Engine in the 1830s.'],
['technology','Internet','hard','Who invented the World Wide Web?','Tim Berners-Lee','Vint Cerf','Steve Jobs','Mark Zuckerberg','Tim Berners-Lee proposed the World Wide Web in 1989 at CERN.'],
// Sports
['sports','Hockey','easy','Which sport is played on ice with sticks and a puck?','Ice hockey','Curling','Field hockey','Polo','Ice hockey players use sticks to shoot a rubber puck.'],
['sports','Football','easy','In football (soccer), which player may handle the ball in the penalty area?','Goalkeeper','Striker','Defender','Midfielder','Only the goalkeeper may handle the ball, inside their own penalty area.'],
['sports','Tennis','easy','Which sport made Sania Mirza famous?','Tennis','Badminton','Squash','Table tennis','Sania Mirza is India\'s most successful woman tennis player, with six Grand Slam doubles titles.'],
['sports','Football','easy','Which card does a football referee show to send a player off?','Red card','Yellow card','Green card','Blue card','A red card means the player must leave the field.'],
['sports','Basketball','medium','How many points is a shot from beyond the arc worth in basketball?','Three','Two','Four','One','A field goal from beyond the three-point line scores three points.'],
['sports','Hockey','medium','Which country has won the most Olympic gold medals in men\'s field hockey?','India','Pakistan','Netherlands','Australia','India has won eight Olympic gold medals in men\'s hockey.'],
['sports','Cricket','medium','What is it called when a bowler takes three wickets in three consecutive balls?','Hat-trick','Maiden','Century','Duck','Three wickets in three consecutive deliveries is a hat-trick.'],
['sports','Athletics','medium','How many events are there in a decathlon?','Ten','Seven','Five','Twelve','Deca means ten; the decathlon has ten track and field events.'],
['sports','Olympics','hard','Which city hosted the first modern Olympic Games in 1896?','Athens','Paris','London','Rome','The first modern Olympics were held in Athens in 1896.'],
['sports','Chess','hard','Who was India\'s first chess grandmaster?','Viswanathan Anand','Pentala Harikrishna','Koneru Humpy','Dibyendu Barua','Viswanathan Anand became India\'s first grandmaster in 1988.'],
// Civics
['civics','Government','easy','Who is the head of the government in India?','Prime Minister','President','Chief Justice','Governor','The Prime Minister leads the Union government.'],
['civics','Rights','easy','What is the name of the right that lets citizens choose their leaders?','Right to vote','Right to travel','Right to silence','Right to property','Voting lets citizens elect their representatives.'],
['civics','Government','easy','What do we call the people elected to make laws?','Legislators','Judges','Police officers','Auditors','Legislators, such as Members of Parliament, make laws.'],
['civics','Constitution','easy','Who is known as the chief architect of the Indian Constitution?','B. R. Ambedkar','Mahatma Gandhi','Sardar Patel','Jawaharlal Nehru','Dr B. R. Ambedkar chaired the Drafting Committee.'],
['civics','Local government','medium','What is a municipal corporation responsible for?','Running a large city\'s local services','Making national laws','Printing currency','Defending borders','Municipal corporations manage city services such as water, roads and waste.'],
['civics','Constitution','medium','How many Fundamental Rights does the Indian Constitution now list?','Six','Seven','Five','Ten','There are six Fundamental Rights since the right to property was removed in 1978.'],
['civics','Judiciary','medium','Which court is the highest court in an Indian state?','High Court','Supreme Court','District Court','Lok Adalat','Each state or group of states has a High Court.'],
['civics','Elections','medium','What is a manifesto?','A party\'s published plans and promises','A voting machine','A court order','A tax form','Parties release manifestos before elections to explain their plans.'],
['civics','Constitution','hard','Which article of the Indian Constitution abolishes untouchability?','Article 17','Article 21','Article 14','Article 370','Article 17 abolishes untouchability and forbids its practice.'],
['civics','Government','hard','Who presides over the Rajya Sabha?','The Vice-President of India','The Prime Minister','The Speaker','The President','The Vice-President is the ex officio Chairman of the Rajya Sabha.'],
// Economics
['economics','Basics','easy','What do we call money a person earns from work?','Income','Debt','Tax','Loan','Income is money received, for example as wages or salary.'],
['economics','Basics','easy','What is a bank account mainly used for?','Keeping and managing money safely','Buying train tickets only','Storing food','Sending letters','Bank accounts hold money and allow payments and savings.'],
['economics','Basics','easy','What do we call goods a country sells to other countries?','Exports','Imports','Subsidies','Tariffs','Exports are goods and services sold abroad.'],
['economics','Money','easy','What is the currency of India?','Indian rupee','Dollar','Taka','Dinar','India\'s currency is the Indian rupee.'],
['economics','Markets','medium','What usually happens to price when demand rises and supply stays the same?','Price rises','Price falls','Price becomes zero','Nothing changes','Higher demand with fixed supply pushes prices up.'],
['economics','Money','medium','What is a budget surplus?','When income is more than spending','When spending is more than income','When taxes are zero','When prices are falling','A surplus means revenue exceeds expenditure.'],
['economics','Banking','medium','What is a loan?','Money borrowed that must be paid back, usually with interest','A gift from a bank','A type of tax','Money earned from work','A loan is borrowed money repaid over time, usually with interest.'],
['economics','Markets','medium','What is it called when a few large firms dominate a market?','Oligopoly','Monopoly','Perfect competition','Barter','An oligopoly is a market controlled by a small number of firms.'],
['economics','Development','hard','What does the Human Development Index combine?','Health, education and income','Exports, imports and taxes','Population, land and rainfall','Prices, wages and rent','The HDI combines life expectancy, schooling and income per person.'],
['economics','Banking','hard','What is the repo rate in India?','The rate at which the RBI lends to banks','The rate banks pay on savings','The income tax rate','The GST rate','The repo rate is what the RBI charges banks for short-term loans.'],
// Music
['music','Notes','easy','How many notes are in a major scale before the octave repeats?','Seven','Five','Eight','Twelve','A major scale has seven different notes, then the eighth repeats the first an octave higher.'],
['music','Indian','easy','What are the seven basic notes of Indian classical music called?','Swaras','Talas','Ragas','Bols','Sa, Re, Ga, Ma, Pa, Dha and Ni are the seven swaras.'],
['music','Terms','easy','What is a group of singers called?','Choir','Orchestra','Band of strings','Quartet of drums','A choir is an organised group of singers.'],
['music','Terms','easy','What do we call the words of a song?','Lyrics','Notes','Chords','Beats','Lyrics are the words that are sung.'],
['music','Terms','medium','What does "fortissimo" mean?','Very loud','Very soft','Very fast','Very slow','Fortissimo, written ff, means very loud.'],
['music','Notes','medium','What is the time value of a whole note in 4/4 time?','Four beats','Two beats','One beat','Eight beats','A whole note lasts four quarter-note beats.'],
['music','Composers','medium','Which composer wrote "The Four Seasons"?','Antonio Vivaldi','Johann Sebastian Bach','Wolfgang Amadeus Mozart','Frédéric Chopin','Vivaldi composed The Four Seasons around 1720.'],
['music','Indian','medium','Who is famous as the "Nightingale of India" for her singing?','Lata Mangeshkar','Asha Bhosle','M. S. Subbulakshmi','Shreya Ghoshal','Lata Mangeshkar was widely called the Nightingale of India.'],
['music','Terms','hard','What is the name for a piece played by a soloist with an orchestra, usually in three movements?','Concerto','Symphony','Sonata','Overture','A concerto features a soloist accompanied by an orchestra.'],
['music','Indian','hard','How many beats are in Teentaal, a common tala in Hindustani music?','Sixteen','Twelve','Ten','Seven','Teentaal has 16 beats divided into four sections of four.'],
// Abbreviations
['abbreviations','Everyday','easy','What does "RSVP" on an invitation ask you to do?','Please reply','Bring a gift','Arrive early','Dress formally','RSVP comes from the French répondez s\'il vous plaît, meaning please reply.'],
['abbreviations','Everyday','easy','What does "FAQ" stand for?','Frequently Asked Questions','Fast Answer Quiz','Final Approved Query','Free Access Question','FAQ pages list frequently asked questions.'],
['abbreviations','Everyday','easy','What does "DIY" stand for?','Do It Yourself','Daily Income Yield','Digital Information Year','Draw It Yearly','DIY means making or fixing something yourself.'],
['abbreviations','Everyday','easy','What does "PTO" at the bottom of a page mean?','Please Turn Over','Print This Out','Page To Open','Pass The Order','PTO means please turn over to the next page.'],
['abbreviations','Technology','medium','In Wi-Fi settings, what does "SSID" stand for?','Service Set Identifier','Secure System ID','Signal Strength Index','Server Side Internet Device','The SSID is the name a wireless network broadcasts.'],
['abbreviations','Organisations','medium','What does "UNICEF" stand for today, after its name changed in 1953?','United Nations Children\'s Fund','United Nations International Cultural Education Fund','Universal Child Education Foundation','United Network for International Child Emergency Funding','In 1953 the name became the United Nations Children\'s Fund, keeping the acronym UNICEF.'],
['abbreviations','India','medium','What does "AIIMS" stand for?','All India Institute of Medical Sciences','Association of Indian Integrated Medical Schools','All India Indian Medical Service','Advanced Institute of Indian Medical Studies','AIIMS is the All India Institute of Medical Sciences.'],
['abbreviations','Technology','medium','What does "OS" stand for in computing?','Operating System','Online Service','Open Software','Output Signal','An operating system manages a device\'s hardware and software.'],
['abbreviations','Science','hard','What does "LASER" stand for?','Light Amplification by Stimulated Emission of Radiation','Light Activated Signal Emitting Ray','Low Angle Shining Electronic Reflector','Linear Amplified Spectrum Emission Radiator','LASER is an acronym describing how a laser produces light.'],
['abbreviations','Organisations','hard','What does "IUCN" stand for?','International Union for Conservation of Nature','Indian Union of Conservation Networks','International United Climate Network','Institute for Universal Clean Nature','The IUCN publishes the Red List of threatened species.'],
// Vocabulary
['vocabulary','Synonyms','easy','Which word means the same as "happy"?','Joyful','Angry','Tired','Hungry','Joyful is a synonym of happy.'],
['vocabulary','Antonyms','easy','What is the opposite of "shallow"?','Deep','Narrow','Wide','Low','Shallow water is not deep.'],
['vocabulary','Synonyms','easy','Which word means "very big"?','Enormous','Tiny','Narrow','Thin','Enormous means extremely large.'],
['vocabulary','Antonyms','easy','What is the opposite of "brave"?','Cowardly','Bold','Daring','Heroic','A cowardly person lacks courage, the opposite of brave.'],
['vocabulary','Meanings','medium','What does "curious" mean?','Eager to know or learn','Very sleepy','Easily angered','Extremely rich','A curious person wants to learn or find out about things.'],
['vocabulary','Meanings','medium','What does "reluctant" NOT mean?','Eager','Unwilling','Hesitant','Disinclined','Reluctant means unwilling or hesitant, so eager is not a meaning.'],
['vocabulary','Spelling','medium','Which spelling is correct?','Rhythm','Rythm','Rhythem','Rithm','Rhythm is spelled r-h-y-t-h-m.'],
['vocabulary','Meanings','medium','What does "vivid" mean?','Bright and clear','Dull and faded','Silent','Broken','Vivid colours or memories are bright, strong and clear.'],
['vocabulary','Meanings','hard','What does "ubiquitous" mean?','Found everywhere','Very rare','Extremely loud','Hard to understand','Something ubiquitous seems to be present everywhere.'],
['vocabulary','Meanings','hard','What does "ephemeral" mean?','Lasting a very short time','Lasting forever','Very heavy','Easy to see','Ephemeral things last only briefly.'],
// Braille
['braille','Contractions','easy','In contracted braille, which word uses all six dots?','For','And','The','With','In Unified English Braille, the full cell with dots 1 to 6 means for.'],
['braille','History','easy','On which date is World Braille Day celebrated?','4 January','15 August','1 May','21 June','World Braille Day is on 4 January, Louis Braille\'s birthday.'],
['braille','Technology','easy','What does a refreshable braille display do?','Raises pins to show braille from a computer or phone','Prints braille on paper','Reads print aloud','Magnifies the screen','A refreshable display raises and lowers small pins to form braille cells.'],
['braille','Basics','easy','What is contracted braille, also called Grade 2?','Braille that uses shortened forms for common words and letter groups','Braille with eight dots','Braille only for numbers','Braille printed in large print','Contractions make braille shorter and faster to read.'],
['braille','Contractions','medium','In contracted braille, which word is dots 1, 2, 3, 4 and 6?','And','For','Of','With','In Unified English Braille, dots 1, 2, 3, 4 and 6 mean and.'],
['braille','Contractions','medium','In contracted braille, which word is dots 2, 3, 4 and 6?','The','And','Of','For','In Unified English Braille, dots 2, 3, 4 and 6 mean the.'],
['braille','Punctuation','medium','Which dots make a question mark in Unified English Braille?','Dots 2, 3 and 6','Dots 2, 5 and 6','Dots 3 and 6','Dots 1, 2 and 6','The UEB question mark is dots 2, 3 and 6.'],
['braille','History','medium','Whose "night writing" system for soldiers inspired Louis Braille?','Charles Barbier','Valentin Haüy','Samuel Morse','Helen Keller','Charles Barbier\'s raised-dot night writing inspired Louis Braille\'s simpler six-dot code.'],
['braille','Contractions','hard','In contracted braille, which word is dots 2, 3, 4, 5 and 6?','With','The','For','And','In Unified English Braille, dots 2, 3, 4, 5 and 6 mean with.'],
['braille','Contractions','hard','In contracted braille, which word is dots 1, 2, 3, 5 and 6?','Of','With','And','The','In Unified English Braille, dots 1, 2, 3, 5 and 6 mean of.'],
// Management
['management','Basics','easy','What is the main job of a team leader?','Guiding a team towards its goals','Doing every task alone','Avoiding meetings','Ignoring problems','A team leader guides and supports the team to reach shared goals.'],
['management','Planning','easy','What is a deadline?','The latest time by which work must be finished','The start of a project','A type of budget','A team meeting','A deadline is the time limit for finishing a task.'],
['management','Time','easy','What is a to-do list used for?','Keeping track of tasks','Counting money','Measuring sales','Hiring staff','A to-do list helps people remember and order their tasks.'],
['management','Communication','easy','What is feedback in the workplace?','Comments that help someone improve','A type of salary','A holiday','A machine','Feedback is information about performance that helps people improve.'],
['management','Planning','medium','What does "SMART" stand for when setting goals?','Specific, Measurable, Achievable, Relevant, Time-bound','Simple, Modern, Accurate, Rapid, Tested','Strong, Motivated, Active, Ready, Tough','Safe, Managed, Approved, Reviewed, Tracked','SMART goals are specific, measurable, achievable, relevant and time-bound.'],
['management','Meetings','medium','What is a meeting agenda?','A list of topics to discuss in a meeting','The minutes after a meeting','A seating plan','A staff salary list','An agenda tells people what a meeting will cover.'],
['management','Time','medium','In the Eisenhower matrix, which tasks should be done first?','Urgent and important','Neither urgent nor important','Important but not urgent','Urgent but not important','Urgent and important tasks go in the do-first quadrant.'],
['management','Teams','medium','What are the stages of team development in Tuckman\'s model, in order?','Forming, storming, norming, performing','Planning, doing, checking, acting','Hiring, training, rewarding, firing','Starting, growing, shrinking, ending','Bruce Tuckman described forming, storming, norming and performing.'],
['management','Theory','hard','Who proposed the hierarchy of needs, with self-actualisation at the top?','Abraham Maslow','Frederick Taylor','Peter Drucker','Henri Fayol','Abraham Maslow proposed his hierarchy of needs in 1943.'],
['management','Theory','hard','Who is known as the father of scientific management?','Frederick Winslow Taylor','Henry Ford','Elton Mayo','Max Weber','F. W. Taylor studied work methods to improve efficiency.'],
// Business
['business','Basics','easy','What do we call a person who buys goods or services from a business?','Customer','Supplier','Manager','Auditor','Customers buy what a business offers.'],
['business','Basics','easy','What is advertising?','Telling people about products to encourage buying','Making products in a factory','Paying staff salaries','Counting stock','Advertising promotes products and services to customers.'],
['business','Basics','easy','What is a shop that sells goods online called?','E-commerce store','Warehouse','Factory','Wholesale market','Online shops are e-commerce stores.'],
['business','Basics','easy','What do we call money a business spends to operate?','Expenses','Revenue','Profit','Equity','Expenses are the costs of running a business.'],
['business','Marketing','medium','What is a slogan?','A short, memorable phrase for a brand','A tax form','A loan','A legal contract','Slogans are catchy phrases used in marketing.'],
['business','Operations','medium','What is quality control?','Checking products meet set standards','Setting product prices','Hiring new staff','Paying suppliers','Quality control checks products or services against standards.'],
['business','Finance','medium','What is a loss?','When expenses are more than revenue','When revenue is more than expenses','A type of brand','A share of a company','A business makes a loss when its costs exceed its income.'],
['business','Strategy','medium','What is diversification?','Adding new products or markets','Closing all branches','Selling only one product','Cutting all prices','Diversification spreads a business into new products or markets.'],
['business','Finance','hard','What is a "unicorn" in the startup world?','A private startup valued at over 1 billion US dollars','A company with one employee','A business that never makes a profit','A government-owned firm','A unicorn is a privately held startup worth more than 1 billion dollars.'],
['business','Strategy','hard','What is a "B2B" business?','One that sells to other businesses','One that sells only to children','One that sells only abroad','One owned by two brothers','B2B means business to business.'],
// Accounting
['accounting','Basics','easy','What does a payslip show?','An employee\'s pay and deductions','A company\'s share price','A customer\'s order','A bank\'s interest rate','A payslip lists gross pay, deductions and net pay.'],
['accounting','Basics','easy','What is a bank statement?','A record of the transactions in a bank account','A loan agreement','A tax return','A shop receipt','A bank statement lists deposits, withdrawals and the balance.'],
['accounting','Basics','easy','What do accountants mainly record and report?','Financial transactions','Weather data','Sports scores','Medical records','Accountants record and report money transactions.'],
['accounting','Basics','easy','What is "cash in hand"?','Money held as notes and coins, not in the bank','Money owed by customers','Money in shares','Money promised for next year','Cash in hand is physical cash kept by the business.'],
['accounting','Principles','medium','What is the going concern assumption?','The business will continue operating in the foreseeable future','The business will close soon','All assets are sold yearly','Profits must be paid out','Financial statements assume the business will keep operating.'],
['accounting','Statements','medium','Which statement shows a company\'s cash inflows and outflows?','Cash flow statement','Balance sheet','Trial balance','Journal','The cash flow statement reports cash coming in and going out.'],
['accounting','Principles','medium','What is the consistency principle?','Using the same accounting methods from period to period','Changing methods every month','Recording only cash sales','Ignoring small expenses','Consistency makes results comparable over time.'],
['accounting','Ratios','medium','What does the current ratio compare?','Current assets with current liabilities','Profit with sales','Shares with debt','Cash with salaries','Current ratio = current assets ÷ current liabilities.'],
['accounting','Principles','hard','What is the prudence (conservatism) principle?','Do not overstate assets or income','Always record maximum profits','Ignore possible losses','Record assets at selling price','Prudence means caution: losses are recognised early, gains only when certain.'],
['accounting','Costs','hard','What is a fixed cost?','A cost that does not change with output in the short run','A cost that rises with each unit made','A cost paid only once ever','A cost refunded by the government','Rent is a typical fixed cost; it stays the same whatever the output.'],
// Commerce
['commerce','Trade','easy','What is a market?','A place or system where buyers and sellers trade','A type of bank','A government office','A factory','A market brings buyers and sellers together.'],
['commerce','Retail','easy','What does a price tag show?','How much an item costs','Where it was made only','Its weight only','Who bought it','A price tag tells shoppers the price of an item.'],
['commerce','Online','easy','What is the shopping cart in an online store?','A list of items you plan to buy','A delivery truck','A payment card','A return form','Online carts hold chosen items until checkout.'],
['commerce','Retail','easy','What is a supermarket?','A large self-service shop selling food and household goods','A wholesale factory','A bank branch','A post office','Supermarkets are large self-service stores.'],
['commerce','Transport','medium','Which mode of transport is usually cheapest for heavy goods over long distances by sea?','Ships','Air freight','Courier bikes','Taxis','Sea shipping is the cheapest way to move bulky goods long distances.'],
['commerce','Payments','medium','What is a cheque?','A written order to a bank to pay a sum','A type of credit card','A tax receipt','A shop discount','A cheque instructs a bank to pay money from the writer\'s account.'],
['commerce','Insurance','medium','What is the principle of "utmost good faith" in insurance?','Both parties must disclose all important facts','Premiums are always refunded','Claims are always paid in full','Insurance is free for the poor','Insurance contracts require full honesty from both sides.'],
['commerce','Trade','medium','What is entrepôt trade?','Importing goods to re-export them','Selling only within a village','Trading only services','Banning all imports','Entrepôt trade imports goods and re-exports them, often after storage.'],
['commerce','Banking','hard','What does IFSC help identify in Indian banking?','A specific bank branch for electronic transfers','A customer\'s income tax','A company\'s shares','A type of insurance','The 11-character IFSC identifies a bank branch for NEFT, RTGS and IMPS.'],
['commerce','Trade','hard','What is the term "FOB" short for in shipping?','Free on Board','Freight on Bank','Final Order Bill','Fixed Outgoing Balance','Under FOB, the seller delivers the goods on board the ship.'],
// Medical
['medical','Body','easy','Which organ helps us breathe?','Lungs','Kidneys','Liver','Stomach','The lungs take in oxygen and remove carbon dioxide.'],
['medical','Health','easy','Why should we wash our hands with soap?','To remove germs','To make them warmer','To grow nails','To change skin colour','Handwashing with soap removes germs that cause illness.'],
['medical','Body','easy','How many teeth does an adult usually have?','32','20','28','36','Adults usually have 32 permanent teeth, including wisdom teeth.'],
['medical','Body','easy','Which organ do we use to think?','Brain','Heart','Lungs','Liver','The brain controls thinking, memory and the body.'],
['medical','Health','medium','Which vaccine-preventable disease is spread by the poliovirus?','Polio','Malaria','Diabetes','Asthma','Polio is caused by the poliovirus and prevented by vaccination.'],
['medical','Body','medium','What carries oxygen in red blood cells?','Haemoglobin','Insulin','Keratin','Melanin','Haemoglobin is the iron-rich protein that carries oxygen.'],
['medical','Health','medium','Which hormone controls blood sugar and is lacking in type 1 diabetes?','Insulin','Adrenaline','Thyroxine','Melatonin','Type 1 diabetes occurs when the pancreas makes little or no insulin.'],
['medical','Health','medium','What is the normal body temperature of a healthy adult, in Celsius?','About 37 degrees','About 30 degrees','About 40 degrees','About 33 degrees','Normal body temperature is around 37 °C.'],
['medical','Body','hard','What is the smallest bone in the human body?','Stapes','Incus','Malleus','Patella','The stapes in the middle ear is the smallest bone.'],
['medical','History','hard','Who developed the first vaccine, against smallpox, in 1796?','Edward Jenner','Louis Pasteur','Jonas Salk','Robert Koch','Edward Jenner used cowpox to protect against smallpox.'],
// Math
['math','Arithmetic','easy','What is 15 + 27?','42','32','41','52','15 + 27 = 42.'],
['math','Arithmetic','easy','What is 9 × 6?','54','45','56','63','9 × 6 = 54.'],
['math','Geometry','easy','How many sides does an octagon have?','Eight','Six','Seven','Ten','An octagon has eight sides.'],
['math','Arithmetic','easy','What is half of 90?','45','40','35','50','90 ÷ 2 = 45.'],
['math','Percentages','medium','What is 25% of 80?','20','25','16','40','25% is one quarter, and 80 ÷ 4 = 20.'],
['math','Geometry','medium','What is the perimeter of a square with sides of 7 centimetres?','28 centimetres','49 centimetres','14 centimetres','21 centimetres','Perimeter = 4 × 7 = 28 centimetres.'],
['math','Numbers','medium','What is 7 squared?','49','14','21','77','7 squared means 7 × 7 = 49.'],
['math','Algebra','medium','If x − 4 = 10, what is x?','14','6','40','10','Add 4 to both sides: x = 10 + 4 = 14.'],
['math','Geometry','hard','What is the sum of the interior angles of a quadrilateral?','360 degrees','180 degrees','270 degrees','540 degrees','Any quadrilateral splits into two triangles, so its angles total 360 degrees.'],
['math','Numbers','hard','What is the value of pi to two decimal places?','3.14','3.41','2.14','3.16','Pi ≈ 3.14159, which is 3.14 to two decimal places.'],
// Physics
['physics','Forces','easy','What do we call a push or a pull on an object?','A force','A mass','A volume','A wave','A force is a push or pull that can change motion.'],
['physics','Light','easy','Which travels faster: light or sound?','Light','Sound','They are equal','Neither moves','Light travels much faster than sound, which is why we see lightning before hearing thunder.'],
['physics','Magnets','easy','What are the two ends of a magnet called?','North and south poles','Top and bottom','Left and right','Plus and minus','Every magnet has a north pole and a south pole.'],
['physics','Sound','easy','What does sound need to travel through?','A medium such as air, water or solids','Only empty space','Only light','Nothing at all','Sound is a vibration that needs a medium; it cannot travel through a vacuum.'],
['physics','Units','medium','What is the SI unit of time?','Second','Minute','Hour','Day','The second is the SI base unit of time.'],
['physics','Heat','medium','What happens to most solids when they are heated?','They expand','They shrink','They become magnetic','They lose mass','Heat makes particles move more and spread apart, so solids expand.'],
['physics','Electricity','medium','What does a fuse do in an electric circuit?','Breaks the circuit if the current is too high','Stores electricity','Increases voltage','Makes the bulb brighter','A fuse melts and breaks the circuit to prevent damage or fire.'],
['physics','Energy','medium','Which device turns electrical energy into motion?','Electric motor','Generator','Battery','Solar cell','An electric motor converts electrical energy into movement.'],
['physics','Sound','hard','About how fast does sound travel in air at room temperature?','343 metres per second','34 metres per second','3,430 metres per second','300,000 kilometres per second','Sound travels about 343 m/s in air at 20 °C.'],
['physics','Modern','hard','What does E = mc² relate?','Energy and mass','Electricity and magnetism','Speed and time','Force and area','Einstein\'s equation shows energy equals mass times the speed of light squared.'],
// Chemistry
['chemistry','Elements','easy','What is the chemical symbol for calcium?','Ca','C','Cl','Co','Calcium\'s symbol is Ca.'],
['chemistry','Elements','easy','Which light gas is used to make party balloons float?','Helium','Oxygen','Carbon dioxide','Chlorine','Helium is lighter than air, so helium balloons float.'],
['chemistry','Everyday','easy','What is the common name for sodium bicarbonate?','Baking soda','Table salt','Sugar','Vinegar','Sodium bicarbonate is known as baking soda.'],
['chemistry','Everyday','easy','Which acid is found in lemons?','Citric acid','Sulfuric acid','Hydrochloric acid','Nitric acid','Citrus fruits contain citric acid.'],
['chemistry','Elements','medium','Which element has the chemical symbol N?','Nitrogen','Neon','Sodium','Nickel','N is the symbol for nitrogen.'],
['chemistry','Reactions','medium','What gas is produced when vinegar reacts with baking soda?','Carbon dioxide','Oxygen','Hydrogen','Chlorine','The reaction releases carbon dioxide bubbles.'],
['chemistry','Reactions','medium','What is rust?','Iron oxide formed when iron reacts with oxygen and water','A type of paint','A kind of salt','Melted iron','Rusting is a slow reaction of iron with oxygen and moisture.'],
['chemistry','Indicators','medium','What colour does blue litmus paper turn in an acid?','Red','Green','Yellow','Black','Acids turn blue litmus paper red.'],
['chemistry','Elements','hard','Which element is the most abundant in Earth\'s crust?','Oxygen','Silicon','Iron','Aluminium','Oxygen makes up about 46% of Earth\'s crust by mass.'],
['chemistry','Bonds','hard','What type of bond forms when atoms share electrons?','Covalent bond','Ionic bond','Metallic bond','Hydrogen bond','In a covalent bond, atoms share pairs of electrons.'],
// Biology
['biology','Plants','easy','What do plants need to make their food?','Sunlight, water and carbon dioxide','Only soil','Only milk','Only moonlight','Plants use sunlight, water and carbon dioxide in photosynthesis.'],
['biology','Animals','easy','Which animals have a backbone?','Vertebrates','Invertebrates','Fungi','Bacteria','Vertebrates are animals with a backbone.'],
['biology','Body','easy','How many chambers does the human heart have?','Four','Two','Three','Six','The heart has two atria and two ventricles.'],
['biology','Life','easy','What do we call a young plant growing from a seed?','Seedling','Stamen','Pollen','Spore','A seedling is a young plant that has just sprouted.'],
['biology','Cells','medium','Which cell structure controls what enters and leaves the cell?','Cell membrane','Nucleus','Ribosome','Vacuole','The cell membrane is selectively permeable.'],
['biology','Body','medium','Which blood cells fight infection?','White blood cells','Red blood cells','Platelets','Plasma cells only','White blood cells defend the body against germs.'],
['biology','Plants','medium','What is the male part of a flower that makes pollen?','Stamen','Pistil','Sepal','Ovary','The stamen consists of the anther, which makes pollen, and the filament.'],
['biology','Ecology','medium','What do we call animals that eat only plants?','Herbivores','Carnivores','Omnivores','Scavengers','Herbivores feed on plants.'],
['biology','Genetics','hard','What are the four bases found in DNA?','Adenine, thymine, guanine, cytosine','Adenine, uracil, guanine, cytosine','Alanine, thymine, glycine, cysteine','Adenine, thymine, glucose, cytosine','DNA uses A, T, G and C; RNA uses uracil instead of thymine.'],
['biology','Cells','hard','Which organelle makes proteins in the cell?','Ribosome','Lysosome','Golgi body','Centriole','Ribosomes join amino acids to build proteins.'],
];
